// src/app/components/enroll/enroll.component.ts
import { Component, inject, OnDestroy } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { AbstractControl, FormControl, FormGroup, ReactiveFormsModule, ValidationErrors, ValidatorFn, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatDividerModule } from '@angular/material/divider';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { AlertService } from '../../services/alert/alert.service';
import { LoginService } from '../../services/login/login.service';


@Component({
  selector: 'app-enroll',
  standalone: true,
  imports: [FlexLayoutModule, MatCardModule, ReactiveFormsModule, RouterModule,  MatFormFieldModule, MatInputModule, MatButtonModule, MatDialogModule, MatDividerModule],
  templateUrl: './enroll.component.html',
  styleUrl: './enroll.component.scss'
})
export class EnrollComponent {
  // route = inject(ActivatedRoute);
  // alert = inject(AlertService);
  // router = inject(Router);
  // loginService = inject(LoginService);
  // dialog = inject(MatDialog)
  
  // formGroup: FormGroup = new FormGroup({})
  // private queryParamSub: Subscription | undefined;

  // constructor() {
  //   this.initForm();
  // }

  // initForm(){
  //   this.formGroup = new FormGroup({
  //     email: new FormControl(null, [Validators.required, Validators.email]),
  //     password: new FormControl(null, [Validators.required]),
  //     confirmPassword: new FormControl(null, [Validators.required]),
  //     firstName: new FormControl(null, [Validators.required]),
  //     lastName: new FormControl(null, [Validators.required]),
  //   }, {
  //     validators:  this.passwordMatchValidator('password', 'confirmPassword')
  //   })
  // }

  // passwordMatchValidator(password: string, confirmPassword: string): ValidatorFn {
  //   return (formGroup: AbstractControl): ValidationErrors | null => {
  //     const passwordControl = formGroup.get(password);
  //     const confirmPasswordControl = formGroup.get(confirmPassword);
  
  //     if (!passwordControl || !confirmPasswordControl) {
  //       return null;
  //     }
  
  //     const isMatch = passwordControl.value === confirmPasswordControl.value;
  //     return isMatch ? null : { passwordMismatch: true };
  //   };
  // }

  // submit(){
  //   if (this.formGroup.valid) {
  //     this.loginService.enroll(this.formGroup.value).subscribe(
  //       {
  //         next: (res: { status: string }) => {
  //           if (res.status === 'success') {
  //             this.alert.successAlert('Enrollment successful. Please proceed to log in.');
  //             this.router.navigate(['login'], { queryParams: {email: btoa(this.formGroup.value.email)}});
  //           }
  //         },
  //         error: (error) => {
  //           this.alert.errorAlert(error?.error?.error || error?.message);
  //         },
  //       }
  //     )
  //   }
  // }

  // ngOnDestroy(): void {
  //   if (this.queryParamSub) {
  //     this.queryParamSub.unsubscribe();
  //   }
  // }
}
<!-- <div fxFlex class="container" fxLayout="row" fxLayoutAlign="center">
  <div fxFlex="70" fxLayout="column" class="left-column" fxLayoutAlign="end start">
  </div>
  <div fxFlex="30" fxLayout="column" fxLayoutAlign="start center">
    <div fxLayout="row" fxLayoutAlign="center" class="mt-100 mb-50">
      <img src="/assets/logo-login.svg" alt="Logo" width="250">
    </div>
    <div fxLayout="row" fxFlex="100" fxLayoutAlign="center start" class="w-100p">
      <div fxLayout="column" fxLayoutAlign="center" class="w-80p">
        <form [formGroup]="formGroup" fxLayout="column" fxLayoutAlign="center" fxLayoutGap="10px" (submit)="submit()">
          <div fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="10px">
            <mat-form-field appearance="outline">
              <mat-label>First Name</mat-label>
              <input formControlName="firstName" matInput type="text" id="firstName">
              <mat-error>First Name is requried</mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline">
              <mat-label>Last Name</mat-label>
              <input formControlName="lastName" matInput type="text" id="lastName">
              <mat-error>Last Name is requried</mat-error>
            </mat-form-field>
          </div>
          <mat-form-field appearance="outline">
            <mat-label>Email</mat-label>
            <input formControlName="email" matInput type="email" id="email">
            <mat-error>Valid Email is requried</mat-error>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Password</mat-label>
            <input formControlName="password" matInput type="password" id="password">
            <mat-error>Password is requried</mat-error>
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Confirm Password</mat-label>
            <input formControlName="confirmPassword" matInput type="password" id="confirmPassword">
          </mat-form-field>
          @if(formGroup.controls['confirmPassword'].dirty && formGroup.errors?.['passwordMismatch']){
          <div
            class="mat-mdc-form-field-subscript-wrapper mat-mdc-form-field-bottom-align mat-mdc-form-field-subscript-dynamic-size">
            <div class="mat-mdc-form-field-error-wrapper" style="opacity: 1; transform: translateY(0%);">
              <mat-error class="mat-mdc-form-field-error mat-mdc-form-field-bottom-align">
                Passwords must match
              </mat-error>
            </div>
          </div>
          }
          <button [disabled]="formGroup.disabled || !formGroup.valid" mat-flat-button color="primary" type="submit"
            class="enroll-btn mt-10 mb-10 p-25">CREATE AN ACCOUNT</button>
        </form>
        <div fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="10" class="mt-10 mb-10">
          <mat-divider class="w-25p"></mat-divider>
          <p class="color-gray">Already a Member ?</p>
          <mat-divider class="w-25p"></mat-divider>
        </div>
        <button mat-stroked-button color="accent" class="mt-10 mb-10 p-25 stroked-btn" [routerLink]="'/login'">SIGN IN</button>
      </div>
    </div>
  </div>
</div> -->

// react/src/components/Enroll/Enroll.tsx
import React, { useState } from 'react';
import styled from 'styled-components';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAlert } from '../../services/alert/alertService';
import { useLogin } from '../../services/login/loginService';

const Container = styled.div`
  display: flex;
  justify-content: center;
  width: 100%;
`;

const LeftColumn = styled.div`
  flex: 70%;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
`;

const RightColumn = styled.div`
  flex: 30%;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const LogoContainer = styled.div`
  display: flex;
  justify-content: center;
  margin: 100px 0 50px;
`;

const Logo = styled.img`
  width: 250px;
`;

const FormContainer = styled.div`
  width: 100%;
  display: flex;
  justify-content: center;
`;

const Form = styled.form`
  width: 80%;
  display: flex;
  flex-direction: column;
  gap: 10px;
`;

const NameFields = styled.div`
  display: flex;
  justify-content: space-between;
  gap: 10px;
`;

const FormField = styled.div`
  width: 100%;
`;

const Input = styled.input`
  width: 100%;
  padding: 12px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  font-size: 16px;
  &:focus {
    outline: none;
    border-color: #1976d2;
  }
`;

const ErrorMessage = styled.div`
  color: #d32f2f;
  font-size: 12px;
  margin-top: 4px;
`;

const Button = styled.button<{ primary?: boolean; stroked?: boolean }>`
  padding: 25px;
  margin: 10px 0;
  border: ${props => props.stroked ? '1px solid #1976d2' : 'none'};
  background-color: ${props => props.primary ? '#1976d2' : 'transparent'};
  color: ${props => props.primary ? 'white' : '#1976d2'};
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
`;

const DividerContainer = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 10px;
  margin: 10px 0;
`;

const Divider = styled.div`
  flex: 1;
  height: 1px;
  background-color: #e0e0e0;
`;

const DividerText = styled.p`
  color: #666;
  margin: 0;
`;

interface FormData {
  email: string;
  password: string;
  confirmPassword: string;
  firstName: string;
  lastName: string;
}

export const Enroll: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { showError, showSuccess } = useAlert();
  const { enroll } = useLogin();
  const [formData, setFormData] = useState<FormData>({
    email: '',
    password: '',
    confirmPassword: '',
    firstName: '',
    lastName: ''
  });
  const [errors, setErrors] = useState<Partial<FormData>>({});

  const validateForm = () => {
    const newErrors: Partial<FormData> = {};
    
    if (!formData.email) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Valid email is required';
    }
    
    if (!formData.password) {
      newErrors.password = 'Password is required';
    }
    
    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Confirm password is required';
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Passwords must match';
    }
    
    if (!formData.firstName) {
      newErrors.firstName = 'First name is required';
    }
    
    if (!formData.lastName) {
      newErrors.lastName = 'Last name is required';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (validateForm()) {
      try {
        const response = await enroll(formData);
        if (response.status === 'success') {
          showSuccess('Enrollment successful. Please proceed to log in.');
          navigate('/login', {
            state: { email: btoa(formData.email) }
          });
        }
      } catch (error: any) {
        showError(error?.error?.error || error?.message);
      }
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  return (
    <Container>
      <LeftColumn />
      <RightColumn>
        <LogoContainer>
          <Logo src="/assets/logo-login.svg" alt="Logo" />
        </LogoContainer>
        <FormContainer>
          <Form onSubmit={handleSubmit}>
            <NameFields>
              <FormField>
                <Input
                  type="text"
                  name="firstName"
                  placeholder="First Name"
                  value={formData.firstName}
                  onChange={handleChange}
                />
                {errors.firstName && <ErrorMessage>{errors.firstName}</ErrorMessage>}
              </FormField>
              <FormField>
                <Input
                  type="text"
                  name="lastName"
                  placeholder="Last Name"
                  value={formData.lastName}
                  onChange={handleChange}
                />
                {errors.lastName && <ErrorMessage>{errors.lastName}</ErrorMessage>}
              </FormField>
            </NameFields>
            <FormField>
              <Input
                type="email"
                name="email"
                placeholder="Email"
                value={formData.email}
                onChange={handleChange}
              />
              {errors.email && <ErrorMessage>{errors.email}</ErrorMessage>}
            </FormField>
            <FormField>
              <Input
                type="password"
                name="password"
                placeholder="Password"
                value={formData.password}
                onChange={handleChange}
              />
              {errors.password && <ErrorMessage>{errors.password}</ErrorMessage>}
            </FormField>
            <FormField>
              <Input
                type="password"
                name="confirmPassword"
                placeholder="Confirm Password"
                value={formData.confirmPassword}
                onChange={handleChange}
              />
              {errors.confirmPassword && <ErrorMessage>{errors.confirmPassword}</ErrorMessage>}
            </FormField>
            <Button type="submit" primary>
              CREATE AN ACCOUNT
            </Button>
          </Form>
        </FormContainer>
        <DividerContainer>
          <Divider />
          <DividerText>Already a Member ?</DividerText>
          <Divider />
        </DividerContainer>
        <Button stroked onClick={() => navigate('/login')}>
          SIGN IN
        </Button>
      </RightColumn>
    </Container>
  );
};
