// react/src/components/Dashboard/Dashboard.tsx
import React, { useEffect, useState } from 'react';
import { useActivity } from '../../services/activity/activityService';
import { useMember } from '../../services/member/memberService';
import { useAlert } from '../../services/alert/alertService';
import { formatCurrency } from '../../utils/stringUtils';
import { StreaksCategory } from '../../enums/streaks-category';
import { StreakPolicy } from '../../models/streak-policy';
import { StreakProgressSelections } from '../../models/streak-progress-selections';
import { Member } from '../../models/member';
import { ColorScheme } from '../../constants/color-scheme';
import { GeneralConstants } from 'constants/general-constants';
import { CouponEnum } from 'enums/coupon-enum';
import { AppTimer } from '../AppTimer/AppTimer';
import { RootState } from 'store';
import { useSelector, useDispatch } from 'react-redux';
import { addMember } from 'store/actions/memberActions';
import '@material-design-icons/font';

interface DashboardProps {
  loyaltyId?: string;
}

export class Widget {
    tierInfo: any;
    totalSpends: number;
    nextTier: string;
    currentTier: string;
    nextMilestone: number;
    hemmingAvailable: number;
    streakBonus: number;
    pointBalance: number;
    tierBenefits: Array<{
        thumbnail: string;
        title: string;
        desc: string[];
    }>;

    constructor(widget: any) {
        this.tierInfo = widget?.data?.lineItems;
        this.totalSpends = widget?.data?.tierProgress ? widget?.data?.tierProgress.nonLinkedBal : 0;
        this.nextTier = widget?.data?.tierProgress ? widget.data?.tierProgress.nextTier : '';
        this.currentTier = widget?.data?.tierProgress ? widget.data?.tierProgress.currentTier : '';
        this.nextMilestone = widget?.data?.tierProgress ? widget.data?.tierProgress.nextMilestone : 0;
        this.pointBalance = (widget?.data?.pointBalance || widget?.data?.pointsBalance) ?? 0;
        this.hemmingAvailable = widget.data?.hemmingAvailable ?? 0;
        this.streakBonus = widget?.data?.streakBonus ?? '';
        this.tierBenefits = widget?.data?.tierBenefits ?? [];

        // if (widget?.data?.aggregates) {
        //     this.aggregates = widget?.data?.aggregates;
        // }
    }
}

// Add color constants
const colors = {
  encore: 'text-primary',
  ruby: 'text-purple-500',
  primary: 'text-primary',
  accent: 'text-accent',
  green: 'text-success',
  gray: 'text-text-secondary'
};

const Dashboard: React.FC<DashboardProps> = ({ loyaltyId = '1001' }) => {
  // Services
  const { getMember, getStreaks } = useMember();
  const { showError } = useAlert();
  const { getActivity, getStreakPolicy } = useActivity();
  const dispatch = useDispatch();

  // State
  const [isLoading, setIsLoading] = useState(true);
  const [widgetSkeleton, setWidgetSkeleton] = useState(true);
  const [streakSkeleton, setStreakSkeleton] = useState(true);
  const [widgetData, setWidgetData] = useState<Widget[]>([]);
  const [streaks, setStreaks] = useState<StreakPolicy[]>([]);
  const [selectedStreakCategory, setSelectedStreakCategory] = useState<StreaksCategory>(StreaksCategory.ACTIVE);
  const [providerPoints, setProviderPoints] = useState<any[]>([]);
  const [streakInfo, setStreakInfo] = useState<any>(null);
  const [steps, setSteps] = useState<StreakPolicy[]>([]);
  const [streakViewProgressSelections, setStreakViewProgressSelections] = useState<StreakProgressSelections>({
    previousTab: StreaksCategory.ACTIVE,
    viewProgressSelections: []
  });
  const member = useSelector((state: RootState) => state.member.member);

  const EXPIRED = 'Expired';
  const COMPLETE = 'Complete';
  const ACTIVE = 'Active';

  useEffect(() => {
    const initializeDashboard = async () => {
      try {
        setIsLoading(true);
        setWidgetSkeleton(true);
        setStreakSkeleton(true);
        
        // Fetch member data
        loyaltyId = '1001';
        const memberData = await getMember(loyaltyId);
        if (memberData) {
          dispatch(addMember(memberData));
          console.log('Member data dispatched to Redux:', memberData);
        }

        // Get widget data
        const widgetPromises = Object.values(CouponEnum).map(val => {
          console.log(val, getActivityPayload(val));
          return getActivity(getActivityPayload(val));
        });
        const widgetResponses: Widget[] = await Promise.all(widgetPromises);
        const processedWidgets = widgetResponses.map(response => new Widget(response));
        setWidgetData(processedWidgets);
        setWidgetSkeleton(false);

        // Get streak policy
        const streakPolicyResponse = await getStreakPolicy();
        setStreakInfo(streakPolicyResponse);
        
        // Initialize steps
        const initializedSteps = streakPolicyResponse.map((data: any) => ({
          ...data,
          icon: 'pending',
          status: 'pending',
          timeRemaining: (data.timeLimit ?? 0) / 1440,
          rewards: data?.ext?.rewards ?? [],
          goals: data?.goalPolicies ?? []
        }));
        setSteps(initializedSteps);

        // Get streaks
        await getStreaksPR(GeneralConstants.streakProgress);

        // Get provider points
        if (memberData?.purses) {
          const points = memberData.purses
            .filter((purse: any) => !purse.name.includes('Status'))
            .map((purse: any) => ({
              provider: purse.name,
              balance: purse.availBalance
            }));
          setProviderPoints(points);
        }

      } catch (error) {
        showError(error instanceof Error ? error.message : 'Failed to initialize dashboard');
      } finally {
        setIsLoading(false);
        setStreakSkeleton(false);
      }
    };

    initializeDashboard();
  }, [loyaltyId]);

  const getActivityPayload = (coupon: string) => {
    return {
      type: coupon === GeneralConstants.streakProgress ? GeneralConstants.streakProgress : 'Personalization',
      date: new Date().toISOString(),
      srcChannelType: 'Web',
      couponCode: coupon === GeneralConstants.streakProgress ? member?.streaks?.[0]?._id || '' : coupon,
      srcChannelID: 'Corporate',
      loyaltyID: member?.loyaltyId || '1001'
    };
  };

  const getStreaksPR = async (code: string, isRefresh: boolean = false) => {
    try {
      setStreakSkeleton(true);
      const payload = {
        type: "Personalization",
        srcChannelType: "Web",
        srcChannelID: "Corporate",
        loyaltyID: member?.loyaltyId || '',
        couponCode: code,
        date: new Date().toISOString()
      };

      const response = await getActivity(payload);
      
      if (response.data?.streaksProgress?.length) {
        const updatedSteps = response.data.streaksProgress.map((sp: any) => ({
          ...sp.streak,
          goalCompleted: `${sp.goals.filter((a: any) => a.status === COMPLETE).length}/${sp.streak.noOfGoals}`,
          icon: getStatusIconName(sp.streak.status),
          goals: sp.goals,
          rewards: sp.streak.rewards ?? (sp.goals.length ? sp.goals.flatMap((a: any) => a.rewards) : []),
          streakId: sp.streakId
        }));
        
        setSteps(updatedSteps);
        
        if (!isRefresh) {
          selectStreakCategory(StreaksCategory.ACTIVE);
        } else {
          prepopulateStreakPrevInfo();
        }
      }
    } catch (error) {
      showError(error instanceof Error ? error.message : 'Failed to fetch streaks');
    } finally {
      setStreakSkeleton(false);
    }
  };

  const selectStreakCategory = (category: StreaksCategory) => {
    setSelectedStreakCategory(category);
    setStreakViewProgressSelections(prev => ({
      ...prev,
      previousTab: category
    }));

    if (category === StreaksCategory.ENDED) {
      setStreaks(steps.filter(data => data.status === COMPLETE || data.status === EXPIRED));
    } else if (category === StreaksCategory.ACTIVE) {
      setStreaks(steps.filter(data => data.status === ACTIVE));
    } else {
      setStreaks(steps);
    }
  };

  const toggleViewProgress = (step: StreakPolicy, streakElemId: string) => {
    const updatedStep = { ...step, displayProgress: !step.displayProgress };
    setSteps(prevSteps => 
      prevSteps.map(s => s.streakId === step.streakId ? updatedStep : s)
    );

    setStreakViewProgressSelections(prev => ({
      ...prev,
      viewProgressSelections: step.displayProgress
        ? prev.viewProgressSelections.filter(id => id !== streakElemId)
        : [...prev.viewProgressSelections, streakElemId]
    }));
  };

  const prepopulateStreakPrevInfo = () => {
    setSelectedStreakCategory(streakViewProgressSelections.previousTab);
    selectStreakCategory(streakViewProgressSelections.previousTab);
    
    if (streakViewProgressSelections.viewProgressSelections.length) {
      setSteps(prevSteps => 
        prevSteps.map(step => ({
          ...step,
          displayProgress: streakViewProgressSelections.viewProgressSelections.includes(step?.streakId || '')
        }))
      );
    }
  };

  const getStatusIconName = (status: string) => {
    if (status === COMPLETE) {
      return 'check_circle';
    } else if (status === ACTIVE) {
      return 'check';
    } else if (status === EXPIRED) {
      return 'warning';
    } else {
      return 'pending';
    }
  };

  const streakOptinPR = async () => {
    try {
      setStreakSkeleton(true);
      const payload = {
        type: "Streak Optin",
        srcChannelType: "Web",
        srcChannelID: "Corporate",
        loyaltyID: member?.loyaltyId || '',
        couponCode: "Double Play Challenge",
        date: new Date().toISOString()
      };

      await getActivity(payload);
      await getStreaksPR(GeneralConstants.streakProgress);
    } catch (error) {
      showError(error instanceof Error ? error.message : 'Failed to opt in to streak');
    } finally {
      setStreakSkeleton(false);
    }
  };

  if (isLoading) {
    return (
      <div className="p-6 text-center">
        <h2 className="text-xl font-semibold">Loading dashboard data...</h2>
      </div>
    );
  }

  return (
    <div className="flex justify-center items-center">
      <div className="container mx-auto px-5 py-6">
        <div className="flex flex-col gap-5 w-full">
          {!widgetSkeleton ? (
            <div className="flex gap-5">
              {/* Member Widget */}
              <div className="w-1/4 bg-white rounded-lg shadow p-6">
                <div className="flex flex-col gap-4">
                  <div className="flex flex-col">
                    <p className="text-gray-600 text-base">Welcome back,</p>
                    <h1 className="text-2xl font-bold text-gray-900">{member?.firstName} {member?.lastName}</h1>
                  </div>
                  <div className="flex flex-col gap-5 mt-2">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-orange-50 flex items-center justify-center">
                        <span className="material-icons text-orange-500">badge</span>
                      </div>
                      <div>
                        <small className="text-gray-500 text-sm block">Loyalty ID</small>
                        <div className="font-medium text-gray-900">{member?.loyaltyId}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-orange-50 flex items-center justify-center">
                        <span className="material-icons text-orange-500">email</span>
                      </div>
                      <div>
                        <small className="text-gray-500 text-sm block">Email</small>
                        <div className="font-medium text-gray-900">{member?.email}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-orange-50 flex items-center justify-center">
                        <span className="material-icons text-orange-500">phone</span>
                      </div>
                      <div>
                        <small className="text-gray-500 text-sm block">Phone</small>
                        <div className="font-medium text-gray-900">{member?.cellPhone}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Tier Status Cards */}
              {widgetData.slice(0, 2).map((widget, index) => (
                <div className="w-1/4 bg-white rounded-lg shadow p-6" key={index}>
                  <div className="flex flex-col">
                    <h3 className="text-lg font-semibold text-gray-900 mb-6">
                      {index === 0 ? 'Encore Tier Status' : 'GCGC Tier Status'}
                    </h3>
                    <div className="flex flex-col items-center">
                      <div className={`flex flex-col items-center ${index === 0 ? 'text-lime-500' : 'text-rose-600'}`}>
                        <div className={`w-20 h-20 rounded-full flex items-center justify-center mb-3 ${
                          index === 0 ? 'bg-lime-500' : 'bg-rose-600'
                        }`}>
                          <span className="material-icons text-white text-3xl">diamond</span>
                        </div>
                        <h2 className="text-xl font-bold mb-6">{widget.currentTier}</h2>
                      </div>
                      {widget.nextTier !== widget.currentTier ? (
                        <div className="w-full">
                          <div className="flex justify-between mb-2">
                            <span className="text-sm text-gray-600">Progress to {widget.nextTier}</span>
                            <span className="text-sm font-medium text-gray-900">
                              {((widget.totalSpends / widget.nextMilestone) * 100).toFixed(0)}%
                            </span>
                          </div>
                          <div className="w-full bg-gray-100 rounded-full h-2 overflow-hidden mb-2">
                            <div 
                              className={`h-2 rounded-full transition-all duration-500 ${index === 0 ? 'bg-lime-500' : 'bg-rose-600'}`}
                              style={{ width: `${(widget.totalSpends / widget.nextMilestone) * 100}%` }}
                            ></div>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-sm text-gray-600">{widget.totalSpends.toLocaleString()} points</span>
                            <span className="text-sm text-gray-600">
                              {(widget.nextMilestone - widget.totalSpends).toLocaleString()} to next tier
                            </span>
                          </div>
                        </div>
                      ) : (
                        <div className="text-green-600 text-center font-medium">
                          Congratulations! You have achieved<br />the Top Tier
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}

              {/* Points Balance Card */}
              <div className="w-1/4 bg-white rounded-lg shadow p-6">
                <div className="flex flex-col gap-6">
                  <h3 className="text-lg font-semibold text-gray-900">Points Balance</h3>
                  <div className="flex flex-col gap-4">
                    {providerPoints.map((provider, index) => (
                      <div key={index} className="flex justify-between items-center">
                        <div className="text-gray-600">{provider.provider}</div>
                        <div className="text-lg font-medium text-gray-900">{provider.balance.toLocaleString()} Points</div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="flex gap-5">
              {[1, 2, 3, 4].map((widget) => (
                <div className="w-1/2 bg-white rounded-lg shadow p-5" key={widget}>
                  <div className="animate-pulse">
                    <div className="h-4 bg-gray-200 rounded w-3/4 mb-4"></div>
                    <div className="h-6 bg-gray-200 rounded w-1/2 mb-6"></div>
                    <div className="space-y-3">
                      <div className="h-4 bg-gray-200 rounded w-full"></div>
                      <div className="h-4 bg-gray-200 rounded w-full"></div>
                      <div className="h-4 bg-gray-200 rounded w-full"></div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          <div className="flex gap-5">
            {/* Tier Benefits Section */}
            <div className="w-1/2 bg-white rounded-lg shadow p-6">
              {!widgetSkeleton ? (
                <>
                  <h3 className="text-lg font-semibold text-gray-900 mb-6">Tier Benefits</h3>
                  <div className="grid grid-cols-2 gap-4">
                    {widgetData[2]?.tierBenefits?.map((benefit, index) => (
                      <div key={index} className="bg-gray-50 rounded-lg p-4 transform transition-transform duration-200 hover:shadow-md">
                        <div className="flex flex-col h-full">
                          <div className="flex items-start gap-4 mb-3">
                            <div className="w-12 h-12 rounded-full bg-orange-50 flex items-center justify-center shrink-0">
                              <span className="material-icons text-orange-500">{benefit.thumbnail}</span>
                            </div>
                            <div className="flex-1">
                              <h3 className="text-gray-900 font-semibold text-base leading-tight mb-1">
                                {benefit.title}
                              </h3>
                            </div>
                          </div>
                          <div className="text-gray-600 text-sm">
                            {benefit.desc.length === 1 ? (
                              <p className="mb-2">{benefit.desc[0]}</p>
                            ) : (
                              <ul className="list-disc pl-4 space-y-1">
                                {benefit.desc.map((desc, idx) => (
                                  <li key={idx}>{desc}</li>
                                ))}
                              </ul>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <div className="space-y-4">
                  {[1, 2].map((row) => (
                    <div className="flex gap-4" key={row}>
                      {[1, 2].map((widget) => (
                        <div className="w-1/2 bg-gray-50 rounded-lg p-4" key={widget}>
                          <div className="animate-pulse">
                            <div className="flex gap-4 mb-4">
                              <div className="w-12 h-12 bg-gray-200 rounded-full"></div>
                              <div className="flex-1">
                                <div className="h-4 bg-gray-200 rounded w-3/4 mb-2"></div>
                              </div>
                            </div>
                            <div className="space-y-2">
                              <div className="h-3 bg-gray-200 rounded w-full"></div>
                              <div className="h-3 bg-gray-200 rounded w-5/6"></div>
                              <div className="h-3 bg-gray-200 rounded w-4/6"></div>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Encore Rewards Challenges Section */}
            <div className="w-1/2 bg-white rounded-lg shadow p-6">
              {!streakSkeleton ? (
                <>
                  <div className="flex justify-between items-center mb-6">
                    <div className="flex items-center gap-2">
                      <h3 className="text-lg font-semibold text-gray-900">Encore Rewards Challenges</h3>
                      <button 
                        onClick={() => getStreaksPR(GeneralConstants.streakProgress, true)}
                        className="p-1.5 rounded-full hover:bg-gray-100 text-gray-600"
                      >
                        <span className="material-icons text-xl">refresh</span>
                      </button>
                    </div>
                    <div className="flex gap-2">
                      {Object.values(StreaksCategory).map((category) => (
                        <button
                          key={category}
                          onClick={() => selectStreakCategory(category)}
                          className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${
                            selectedStreakCategory === category
                              ? 'bg-orange-500 text-white'
                              : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                          }`}
                        >
                          {category}
                        </button>
                      ))}
                    </div>
                  </div>

                  {streaks.length === 0 ? (
                    <div className="flex flex-col items-center justify-center py-12">
                      <div className="text-center text-gray-600 mb-6">
                        {selectedStreakCategory === StreaksCategory.ACTIVE ? (
                          <>
                            <p className="mb-1">You are currently not participating in any challenges</p>
                            <p>Join a challenge to start earning rewards!</p>
                          </>
                        ) : (
                          <p>You haven't completed any challenges yet</p>
                        )}
                      </div>
                      {selectedStreakCategory === StreaksCategory.ACTIVE && (
                        <button 
                          onClick={streakOptinPR}
                          className="px-6 py-2 bg-orange-500 text-white rounded-lg font-medium hover:bg-orange-600 transition-colors"
                        >
                          Get Started
                        </button>
                      )}
                    </div>
                  ) : (
                    <div className="space-y-6">
                      {streaks.map((step, index) => (
                        <div key={index} className="bg-gray-50 rounded-lg p-5">
                          <div className="flex gap-6">
                            {/* Left side - Progress */}
                            <div className="w-3/5">
                              <div className="flex items-center gap-3 mb-4">
                                <h3 className="text-lg font-bold text-gray-900">{step.name}</h3>
                                <span className="text-2xl">🎪</span>
                              </div>
                              {!step.goals.length ? (
                                <div className="text-gray-600">{step.streakGoalMessage}</div>
                              ) : (
                                <div className="space-y-4">
                                  {step.goals.map((goal, goalIndex) => (
                                    <div key={goalIndex} className="space-y-2">
                                      <div className="flex items-center gap-3">
                                        <span className="w-2 h-2 rounded-full bg-orange-500"></span>
                                        <span className="font-medium text-gray-900">
                                          {goal.name}: {formatCurrency(goal.value || 0)}/{formatCurrency(goal.target)}
                                        </span>
                                      </div>
                                      <div className="w-full bg-gray-200 rounded-full h-1.5">
                                        <div 
                                          className="h-1.5 rounded-full bg-orange-500"
                                          style={{ width: `${((goal.value || 0) / goal.target) * 100}%` }}
                                        ></div>
                                      </div>
                                      {goal.instantBonus && (
                                        <div className="text-sm text-gray-600 pl-5">
                                          Bonus earned so far: {goal.instantBonus}
                                        </div>
                                      )}
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>

                            {/* Right side - Info */}
                            <div className="w-2/5">
                              <p className="text-gray-600 text-sm mb-4">{step.desc}</p>
                              {step.startedAt && step.timeLimit && step.status === 'Active' && (
                                <div className="inline-block px-3 py-1 bg-gray-600 text-white text-sm rounded-full mb-4">
                                  <AppTimer startedAt={step.startedAt} timeLimit={step.timeLimit} />
                                </div>
                              )}
                              <div className="flex gap-3">
                                <div className="flex-1 bg-white rounded-lg p-3">
                                  <div className="text-sm text-gray-600 mb-1">Status</div>
                                  <div className="flex items-center gap-2">
                                    <span className={`w-2 h-2 rounded-full ${
                                      step.status === 'Complete' ? 'bg-green-500' :
                                      step.status === 'Active' ? 'bg-orange-500' :
                                      'bg-red-500'
                                    }`}></span>
                                    <span className="font-semibold text-gray-900">
                                      {step.status === 'Complete' ? 'Completed' : step.status}
                                    </span>
                                  </div>
                                </div>
                                <div className="flex-1 bg-white rounded-lg p-3">
                                  <div className="text-sm text-gray-600 mb-1">Goals</div>
                                  <div className="font-semibold text-gray-900">{step.goalCompleted}</div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </>
              ) : (
                <div className="space-y-4">
                  {[1, 2, 3].map((widget) => (
                    <div className="bg-gray-50 rounded-lg p-5" key={widget}>
                      <div className="animate-pulse">
                        <div className="h-6 bg-gray-200 rounded w-1/4 mb-4"></div>
                        <div className="space-y-3">
                          <div className="h-4 bg-gray-200 rounded w-full"></div>
                          <div className="h-4 bg-gray-200 rounded w-5/6"></div>
                          <div className="h-4 bg-gray-200 rounded w-4/6"></div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;

// src/app/components/dashboard/dashboard.component.ts
import { CommonModule } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, Component, OnDestroy, OnInit, inject } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatDialog } from '@angular/material/dialog';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { Router, RouterModule } from '@angular/router';
import { State, Store } from '@ngrx/store';
import { Color, NgxChartsModule } from '@swimlane/ngx-charts';
import { Observable, Subscription, forkJoin } from 'rxjs';
import { Streaks } from '../../classes/streaks/streaks';
import { Widget } from '../../classes/widget/widget';
import { ColorScheme } from '../../constants/color-scheme';
import { GeneralConstants } from '../../constants/general-constants';
import { StreaksConstants } from '../../constants/streaks-constants';
import { CouponEnum } from '../../enums/coupon-enum';
import { StreaksCategory } from '../../enums/streaks-category';
import { Member } from '../../models/member';
import { StreakPolicy } from '../../models/streak-policy';
import { StreakProgressSelections } from '../../models/streak-progress-selections';
import { StandardCurrencyPipe } from "../../pipes/standard-currency/standard-currency.pipe";
import { ActivityService } from '../../services/activity.service';
import { AlertService } from '../../services/alert/alert.service';
import { MemberService } from '../../services/member/member.service';
import { AppTimerComponent } from '../app-timer/app-timer.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [MatCardModule, RouterModule, FlexLayoutModule, CommonModule, MatProgressBarModule, MatIconModule, MatButtonModule, NgxChartsModule, MatDividerModule, StandardCurrencyPipe, MatChipsModule,
    AppTimerComponent
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent implements OnInit, OnDestroy {
  private store = inject(Store);
  state = inject(State);
  private readonly EXPIRED = 'Expired';
  private readonly COMPLETE = 'Complete';
  private readonly ACTIVE = 'Active'

  memberInfo?: Member;
  memberTier = "";
  colorScheme: Color = ColorScheme;
  widgetData: any = [];
  streaks: StreakPolicy[] = [];
  minThreshold: number = 0;
  maxThreshold: number = 100;
  widgetSkeleton = true;
  streakSkeleton = true;
  subscriptions: Subscription[] = [];
  chartData = [];
  streakInfo: any;
  streakBonus: number = 0;
  panelOpenState = false;
  displayStreakProgress = false;

  steps: StreakPolicy[] = [];
  selectedStreakCategory: StreaksCategory = StreaksCategory.ACTIVE;

  streakCategories: StreaksCategory[] = [StreaksCategory.ACTIVE, StreaksCategory.Ended];
  streakViewProgressSelections: StreakProgressSelections = { previousTab: StreaksCategory.ACTIVE, viewProgressSelections: [] };
  providerPoints: any = []
  constructor(
    private memberService: MemberService,
    private alertService: AlertService,
    private activityService: ActivityService,
    private router: Router,
    public dialog: MatDialog,
  ) { }
  ngOnInit() {
    this.subscriptions.push(
      this.store.select('member').subscribe((member: Member) => {
        if (Object.keys(member).length) {
          this.widgetSkeleton = true;
          this.streakSkeleton = true;
          this.memberInfo = member;
          this.memberTier = this.memberInfo.tiers[0].level.name;
          this.getWidgetData();
          this.getPurseValues();
          this.getStreakInfo();
        }
      })
    );
  }

  getPurseValues() {
    if (this.memberInfo) {
      this.providerPoints = this.memberInfo.purses.filter((purse) => !purse.name.includes('Status')).map((purse) => ({
        provider: purse.name,
        balance: purse.availBalance
      }))
    }
  }

  calculateAverage = (streak) => (streak.target ? ((streak.value / streak.target) * 100)?.toFixed(0) : 0);

  getChartData(streak) {
    return [{ name: streak.name, value: streak.value }]
  }

  isString = (value) => typeof value === 'string';
  isArray = (value) => Array.isArray(value) && value.every(item => item && typeof item.title === 'string');

  isGoalsCompleted = () => this.streaks.every((streak) => streak.status === 'Complete');

  async getStreakInfo(isRefresh: boolean = false) {
    this.activityService.getStreakPolicy().subscribe({
      next: (res) => {
        this.streakSkeleton = true;
        this.streakInfo = res;
        this.steps = this.streakInfo.map((data) => {
          return {
            ...data,
            icon: 'pending',
            status: 'pending',
            timeRemaining: (data.timeLimit ?? 0) / 1440,
            rewards: data?.ext?.rewards ?? [],
            goals: data?.goalPolicies ?? []
          }

        });
        this.fetchStreaks(isRefresh);
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
        this.streakSkeleton = false;
      },
    });
  }

  async fetchStreaks(isRefresh: boolean = false) {
    try {
      await this.getStreaksPR(GeneralConstants.streakProgress, isRefresh);
      //await this.getStreaks(isRefresh);
    } catch (error: any) {
      this.alertService.errorAlert(error?.error?.error || error?.message);
    }

  }

  updateConstant() {
    StreaksConstants.forEach((streak, idx) => {
      const matchingPolicy = this.streakInfo.goals[idx];
      if (matchingPolicy) {
        streak.desc = matchingPolicy.description;
      }
    });
  }

  async getStreaks(isRefresh: boolean = false) {
    this.streakSkeleton = true;
    await this.memberService.getStreaks(this.memberInfo?._id ?? '').subscribe({
      next: (streaksResp: any) => {
        this.streakSkeleton = false;
        if (isRefresh) {
          this.prepopulateStreakPrevInfo();
        }
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
        this.streakSkeleton = false;
      },
    });
  }

  getStreakBonus() {
    this.activityService.getActivity(this.getActivityPayload(GeneralConstants.streakProgress)).subscribe({
      next: (res: any) => this.streakBonus = res.data.streakProgress?.streakBonus,
      error: (error) => this.alertService.errorAlert(error?.error?.error || error?.message)
    })
  }

  getWidgetData() {
    const request: Observable<any>[] = [];
    Object.values(CouponEnum).forEach((val) => (request.push(
      this.activityService.getActivity(this.getActivityPayload(val))
    )));
    forkJoin(request).subscribe({
      next: (widgets: Widget[]) => {
        this.widgetData = widgets.map((widget: Widget) => new Widget(widget));
        this.widgetSkeleton = false;
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
        this.widgetData = Object.values(CouponEnum).map(() => new Widget({}));
        this.widgetSkeleton = false
      }
    });
  }

  getActivityPayload(coupon: string) {
    return {
      type: coupon === GeneralConstants.streakProgress ? GeneralConstants.streakProgress : 'Personalization',
      date: new Date().toISOString(),
      srcChannelType: 'Web',
      couponCode: coupon === GeneralConstants.streakProgress ? this.memberInfo?.streaks[0]?._id : coupon,
      srcChannelID: 'Corporate',
      loyaltyID: this.memberInfo?.loyaltyId
    };
  }

  navigateToRewards() {
    this.router.navigate(['/rewards'], { fragment: 'Vouchers' });
  }

  navigateToGoals(streak: Streaks) {
    this.router.navigate([streak.url], { fragment: streak.fragment ?? '' })
  }
  selectStreakCategory(category: StreaksCategory) {
    this.selectedStreakCategory = category;
    this.streakViewProgressSelections.previousTab = this.selectedStreakCategory;
    if (this.selectedStreakCategory === StreaksCategory.Ended) {
      this.streaks = this.steps.filter((data) => data.status === this.COMPLETE || data.status === this.EXPIRED);
    } else if (this.selectedStreakCategory === StreaksCategory.ACTIVE) {
      this.streaks = this.steps.filter((data) => data.status === this.ACTIVE);
    } else {
      this.streaks = this.steps;
    }
  }

  async getStreaksPR(code: string, isRefresh: boolean = false) {
    this.streakSkeleton = true;
    let payload = {
      type: "Personalization",
      srcChannelType: "Web",
      srcChannelID: this.state.getValue().location.location,
      loyaltyID: this.memberInfo?.loyaltyId,
      couponCode: code,
      date: new Date().toISOString()
    }
    await this.activityService.getActivity(payload).subscribe({
      next: (res: any) => {
        this.streakSkeleton = false;
        if (res.data?.streaksProgress?.length) {
          this.steps = res.data?.streaksProgress.map(sp => ({
            ...sp.streak,
            goalCompleted: `${sp.goals.filter(a => a.status === this.COMPLETE).length}/${sp.streak.noOfGoals}`,
            icon: this.getStatusIconName(sp.streak.status),
            goals: sp.goals,
            rewards: sp.streak.rewards ?? (sp.goals.length ? sp.goals.flatMap(a => a.rewards) : []),
            streakId: sp.streakId
          }))
          if (!isRefresh) {
            this.selectStreakCategory(StreaksCategory.ACTIVE);
          }
          else {
            this.prepopulateStreakPrevInfo();
          }
        }
      },
      error: (error) => {
        this.streakSkeleton = false;
        this.alertService.errorAlert(error?.error?.error || error?.message)
      }
    })
  }

  toggleViewProgress(step: StreakPolicy, streakElemId: string) {
    if (step) {
      step.displayProgress = !step.displayProgress;
      if (step.displayProgress) {
        this.streakViewProgressSelections.viewProgressSelections.push(streakElemId);
      }
      else {
        this.streakViewProgressSelections.viewProgressSelections = this.streakViewProgressSelections.viewProgressSelections.filter((ids: string) => ids != streakElemId);
      }
    }
  }

  prepopulateStreakPrevInfo() {
    this.selectedStreakCategory = this.streakViewProgressSelections.previousTab;
    this.selectStreakCategory(this.selectedStreakCategory);
    if (this.streakViewProgressSelections.viewProgressSelections.length) {
      this.streakViewProgressSelections.viewProgressSelections.forEach((streakId: string) => {
        this.streaks.filter(streak => streak.streakId == streakId).forEach(streak => streak.displayProgress = true);
      });
    }
  }

  getStatusIconName(status: string) {
    if (status === this.COMPLETE) {
      return 'check_circle';
    } else if (status === this.ACTIVE) {
      return 'check';
    } else if (status === this.EXPIRED) {
      return 'warning';
    } else {
      return 'pending';
    }
  }

  async streakOptinPR() {
   
    this.streakSkeleton = true;
    let payload = {
      type: "Streak Optin",
      srcChannelType: "Web",
      srcChannelID: this.state.getValue().location.location,
      loyaltyID: this.memberInfo?.loyaltyId,
      couponCode: "Double Play Challenge",
      date: new Date().toISOString()
    }
    await this.activityService.getActivity(payload).subscribe({
      next: (res: any) => {
        this.streakSkeleton = false;
        this.fetchStreaks();
      },
      error: (error) => {
        this.streakSkeleton = false;
        this.alertService.errorAlert(error?.error?.error || error?.message)
      }
    })
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(x => x.unsubscribe())
  }
}
<div fxLayout="row" fxLayoutAlign="center center">
  <div fxLayout="row" class="w-1300 p-20">
    <div fxFlex="100" fxLayout="row" fxLayoutGap="20">
      <div fxLayout="column" fxLayoutGap="20" fxLayoutAlign="start stretch" fxFlex="100">
        @if(!widgetSkeleton ) {
        <div fxLayout="row" fxLayoutGap="20">
          <!-- Member Widget -->
          <mat-card class="p-20 card-style" fxFlex="25">
            <div class="welcome-section">
              <div class="user-header">
                <div class="user-welcome">
                  <h2 class="welcome-text">Welcome back,</h2>
                  <h1 class="user-name">{{memberInfo?.firstName}} {{memberInfo?.lastName}}</h1>
                </div>
              </div>
              <div class="user-details">
                <div class="detail-item" fxLayout="row" fxLayoutAlign="start center">
                  <mat-icon>badge</mat-icon>
                  <span>
                    <small class="label">Loyalty ID</small>
                    <div class="value">{{memberInfo?.loyaltyId}}</div>
                  </span>
                </div>
                <div class="detail-item" fxLayout="row" fxLayoutAlign="start center">
                  <mat-icon>email</mat-icon>
                  <span>
                    <small class="label">Email</small>
                    <div class="value">{{memberInfo?.email || '-'}}</div>
                  </span>
                </div>
                <div class="detail-item" fxLayout="row" fxLayoutAlign="start center">
                  <mat-icon>calendar_today</mat-icon>
                  <span>
                    <small class="label">Member Since</small>
                    <div class="value">{{memberInfo?.enrollDate | date}}</div>
                  </span>
                </div>
              </div>
            </div>
          </mat-card>
          <!-- Encore Status -->
          @for(widget of widgetData; track $index;){
          @if($index <2){<mat-card class="p-20 card-style" fxFlex="25">
            <div class="tier-status-section">
              <h3 class="section-title">{{$index === 0 ? 'Encore Tier Status' : 'GCGC Tier Status'}}</h3>
              <div class="tier-card">
                <div class="tier-badge" [ngClass]="{'encore': $index === 0, 'ruby': $index !== 0}">
                  <div class="tier-icon-wrapper">
                    <mat-icon class="tier-icon">diamond</mat-icon>
                  </div>
                  <h2>{{widget.currentTier}}</h2>
                </div>
                <div class="tier-progress">
                  @if(widget.nextTier !== widget.currentTier){
                  <div fxLayout="row" fxLayoutAlign="space-between center">
                    <span class="progress-label">Progress to {{widget.nextTier}}</span>
                    <span class="progress-percentage">{{(widget.totalSpends / widget.nextMilestone *
                      100).toFixed(0)}}%</span>
                  </div>
                  <mat-progress-bar mode="determinate" [value]="(widget.totalSpends / widget.nextMilestone) * 100"
                    class="tier-progress-bar">
                  </mat-progress-bar>
                  <div class="progress-stats">
                    <span class="current-points">{{widget.totalSpends | number}} points</span>
                    <span class="points-needed">{{(widget.nextMilestone - widget.totalSpends) | number}} to next
                      tier</span>
                  </div>
                  }@else{
                  <span class="color-green text-center winning-text">Congratulations! You have achieved the Top
                    Tier</span>
                  }
                </div>
              </div>
            </div>
            </mat-card>
            }
            }
            <mat-card class="p-20 card-style" fxFlex="25">
              <div class="points-balance-section">
                <h3 class="section-title">Points Balance</h3>
                <div class="balance-cards">
                  <div class="provider-points">
                    @for(provider of providerPoints; track provider.provider) {
                    <div class="provider-item">
                      <div class="provider-name">{{provider.provider}}</div>
                      <div class="provider-value">{{provider.balance | number: '1.0-0'}} Points</div>
                    </div>
                    }
                  </div>
                </div>
              </div>
            </mat-card>
        </div>
        }
        @else {
        <div fxLayout="row" fxLayoutGap="20">
          @for(widget of [1,2,3,4]; track widget){
          <mat-card class="p-20 card-style" fxFlex="50">
            <mat-card-content class="skeleton">
              <div class="skeleton-left">
                <div class="line h-10 w-90p mb-15"></div>
                <div class="line h-15 w-30p mb-20"></div>
                <div class="line h-20 w-100p mb-20"></div>
                <div class="line h-20 w-100p mb-20"></div>
                <div class="line h-20 w-100p mb-20"></div>
                <div class="line h-20 w-100p mb-20"></div>
              </div>
            </mat-card-content>
          </mat-card>
          }
        </div>
        }

        <div fxFlex="100" fxLayout="row" fxLayoutGap="20">
          <div fxLayout="column" class="card-style bg-white p-20" fxFlex="50">
            @if(!widgetSkeleton ) {
            <h3 class="mt-10 mb-20">Tier Benefits</h3>
            <div fxFlex fxLayout="row wrap" fxLayoutGap="20px grid">
              @for (benefits of widgetData[2]?.tierBenefits; track $index) {
              <div fxFlex="50" fxLayoutAlign="start stretch" class="benefit-list">
                <mat-card class="card-style benefit-card p-10 h-100p" fxFlexFill>
                  <mat-card-content fxLayout="column" fxLayoutGap="0" fxFlex="1 1 auto" class="p-0">
                    <div fxLayout="row" fxLayoutAlign="start start" class="perk-header" fxLayoutGap="10">
                      <div class="benefit-thumbnail" fxLayoutAlign="center center">
                        <mat-icon color="primary">{{ benefits.thumbnail }}</mat-icon>
                      </div>
                      <div fxFlex fxLayout="column" fxLayoutAlign="center start" class="perk-card">
                        <h3 class="color-accent title">{{ benefits.title }}</h3>
                      </div>
                    </div>
                    <div fxFlex="1 1 auto" class="desc-container">
                      @if(benefits.desc.length === 1) {
                      <div class="mb-2 mt-0 mt-4">{{ benefits.desc[0] }}</div>
                      } @else {
                      <ul class="pl-20 mb-2 mt-0 mt-4">
                        @for(desc of benefits.desc; track desc) {
                        <li><span>{{ desc }}</span></li>
                        }
                      </ul>
                      }
                    </div>
                  </mat-card-content>
                </mat-card>
              </div>
              }
            </div>

            }@else{
            @for(row of [1,2]; track row){
            <div fxLayout="row" fxLayoutGap="10">
              @for(widget of [1,2,3]; track widget){
              <mat-card class="p-5" fxFlex="50">
                <mat-card-content class="skeleton">
                  <div class="skeleton-left">
                    <div class="line h-80 w-100p mb-10"></div>
                    <div class="line h-12 w-100p mb-10"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                  </div>
                </mat-card-content>
              </mat-card>
              }
            </div>
            }
            }
          </div>
          <div fxLayout="column" class="card-style bg-white p-20" fxFlex="50">

            @if (!streakSkeleton) {
            <div fxLayout="row" fxLayoutAlign="space-between center">
              <div fxLayout="row" fxLayoutAlign="center">
                <h3 class="mt-10 mb-20">Encore Rewards Challenges</h3>
                <button mat-icon-button class="refresh-btn" (click)="getStreakInfo(true)">
                  <mat-icon>refresh</mat-icon>
                </button>
              </div>
              <div class="filter-container mb-20">
                <small>
                  <mat-chip-listbox hideSingleSelectionIndicator>
                    @for (category of streakCategories; track $index) {
                    <mat-chip-option (selectionChange)="selectStreakCategory(category)"
                      [selected]="selectedStreakCategory === category"
                      [class.disable-click]="selectedStreakCategory === category">
                      {{ category }}
                    </mat-chip-option>
                    }
                  </mat-chip-listbox>
                </small>
              </div>
            </div>

            @if (!streaks.length) {
            <div fxLayout="column" fxLayoutAlign="center center" class="empty-challenges p-20">
              <div class="text-center color-gray mb-20">
                @if (selectedStreakCategory === 'Active') {
                <p>You are currently not participating in any challenges</p>
                <p>Join a challenge to start earning rewards!</p>
                } @else {
                <p>You haven't completed any challenges yet</p>
                }
              </div>

              @if (selectedStreakCategory === 'Active') {
              <button mat-raised-button color="primary" class="get-started-btn" (click)="streakOptinPR()">
                Get Started
              </button>
              }
            </div>
            }

            @for (step of streaks; track $index; let last = $last) {
            <div class="mb-20">
              <div class="streak-card" fxLayout="row" fxLayoutGap="24px">
                <!-- Left side - Progress -->
                <div fxFlex="60" fxLayout="column" fxLayoutGap="16px">
                  <div fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="8px" class="mb-10">
                    <h3 mat-line class="mat-title text-gray-900 font-bold">{{ step.name }}</h3>
                    <span class="text-xl">🎪</span>
                  </div>
                  @if (!step.goals.length) {
                  <div>{{step.streakGoalMessage}}</div>
                  }
                  @for (goal of step.goals; track $index) {
                  <div fxLayout="column" fxLayoutGap="6px">
                    <div fxLayout="row" fxLayoutAlign="start center">
                      <div fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="8px" class="mr-5">
                        <span class="w-8 h-8 rounded-full bg-orange-500"></span>
                      </div>
                      <span class="font-medium text-gray-900 text-sm">
                        <b>
                          {{ goal.name }}: {{ (goal.value || 0 )|standardCurrency: '1.0-0' }}/{{ goal.target
                          |standardCurrency : '1.0-0' }}
                        </b>
                      </span>
                    </div>
                    <mat-progress-bar color="primary" mode="determinate" [value]="(goal.value || 0) / goal.target * 100"
                      class="h-6">
                    </mat-progress-bar>
                    <div fxLayout="row" fxLayoutAlign="space-between center">
                      <div>
                        @if (goal?.instantBonus) {
                        <div fxLayout="row" fxLayoutAlign="space-between start">
                          <small><b class="pr-4">Bonus earned so far: </b>{{goal.instantBonus}}</small>
                        </div>
                        }

                      </div>
                    </div>
                  </div>
                  }
                </div>

                <!-- Right side - Info -->
                <div fxFlex="40" fxLayout="column" fxLayoutGap="16px">
                  <p class="text-gray-600 text-sm">{{ step.desc }}</p>
                  @if (step.startedAt && step.timeLimit && step.status === 'Active') {
                  <div class="bg-gray-500 text-white text-sm px-3 py-0.5 rounded-full inline-block width-fit-content">
                    <app-app-timer [startedAt]="step.startedAt" [timeLimit]="step.timeLimit"></app-app-timer>
                  </div>
                  }
                  <div fxLayout="row" fxLayoutGap="12px">
                    <div fxFlex class="bg-gray-50 rounded-lg p-2 status-card" fxLayout="column" fxLayoutGap="4px">
                      <div class="text-sm font-medium text-gray-500">Status</div>
                      <div fxLayout="row" fxLayoutAlign="start center" fxLayoutGap="8px">
                        <span class="w-8 h-8 rounded-full"
                          [ngClass]="{'bg-green-500': step.status === 'Complete', 'bg-green': step.status === 'Active', 'bg-red': step.status === 'Expired'}">
                        </span>
                        <span class="font-semibold text-gray-900">
                          {{ step.status === 'Complete' ? 'Completed' : step.status }}
                        </span>
                      </div>
                    </div>
                    <div fxFlex class="bg-gray-50 rounded-lg p-2 status-card" fxLayout="column" fxLayoutGap="4px">
                      <div class="text-sm font-medium text-gray-500">Goals</div>
                      <div class="font-semibold text-gray-900">{{ step.goalCompleted }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            }
            } @else {
            <div fxLayout="column" fxLayoutGap="10">
              @for(widget of [1,2,3]; track widget){
              <mat-card class="p-5" fxFlex="50">
                <mat-card-content class="skeleton">
                  <div class="skeleton-left">
                    <div class="line h-40 w-100p mb-10"></div>
                    <div class="line h-12 w-100p mb-10"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                    <div class="line h-10 w-100p mb-5"></div>
                  </div>
                </mat-card-content>
              </mat-card>
              }
            </div>
            }
          </div>

        </div>

      </div>
    </div>
