// react/src/components/Locations/Locations.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useDispatch, useSelector } from 'react-redux';
import { useLocation } from '../../services/location/locationService';
import { useAlert } from '../../services/alert/alertService';
import { setLocation } from '../../store/actions/locationActions';

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
`;

const FormField = styled.div`
  width: 100%;
  padding: 0;
`;

const SelectContainer = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
`;

const Icon = styled.span`
  font-family: 'Material Symbols Outlined';
  font-size: 20px;
`;

const Select = styled.select`
  width: 100%;
  padding: 12px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  font-size: 16px;
  background-color: white;
  &:focus {
    outline: none;
    border-color: #1976d2;
  }
`;

interface Location {
  name: string;
  number: string;
  ext: {
    hideInMSSP?: boolean;
    operator?: string;
  };
}

export const Locations: React.FC = () => {
  const [allLocations, setAllLocations] = useState<Location[]>([]);
  const [selectedLocation, setSelectedLocation] = useState('');
  const { getLocations } = useLocation();
  const { showError } = useAlert();
  const dispatch = useDispatch();

  useEffect(() => {
    const fetchLocations = async () => {
      try {
        const locations = await getLocations();
        const filteredLocations = locations.filter((location: Location) => !location.ext.hideInMSSP);
        setAllLocations(filteredLocations);
        if (filteredLocations.length > 0) {
          setSelectedLocation(filteredLocations[0].name);
          handleLocationChange(filteredLocations[0].name);
        }
      } catch (error: any) {
        showError(error?.error?.error || error?.message);
      }
    };

    fetchLocations();
  }, []);

  const handleLocationChange = (locationName: string) => {
    const location = allLocations.find(loc => loc.name === locationName);
    if (location) {
      dispatch(setLocation(location.number));
    }
  };

  if (!allLocations.length) {
    return null;
  }

  return (
    <Container>
      <FormField>
        <label>Property Name</label>
        <SelectContainer>
          <Icon>distance</Icon>
          <Select
            value={selectedLocation}
            onChange={(e) => {
              setSelectedLocation(e.target.value);
              handleLocationChange(e.target.value);
            }}
          >
            {allLocations.map((location) => (
              <option key={location.name} value={location.name}>
                {location.ext.operator && location.ext.operator !== 'PlayNow'
                  ? `${location.ext.operator} - ${location.name}`
                  : location.name}
              </option>
            ))}
          </Select>
        </SelectContainer>
      </FormField>
    </Container>
  );
};

// src/app/components/locations/locations.component.ts
import { Component, inject } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatSelectModule } from '@angular/material/select';
import { Store } from '@ngrx/store';
import { take } from 'rxjs';
import { AlertService } from '../../services/alert/alert.service';
import { LocationService } from '../../services/location/location.service';
import { setLocation } from '../../states/actions/location.action';
import { UnsubscribeComponent } from '../common/unsubscribe/unsubscribe.component';

@Component({
  selector: 'app-locations',
  standalone: true,
  imports: [FlexLayoutModule, MatButtonModule, MatMenuModule, MatIconModule, MatFormFieldModule, MatInputModule, MatAutocompleteModule, ReactiveFormsModule, MatSelectModule],
  templateUrl: './locations.component.html',
  styleUrl: './locations.component.scss'
})
export class LocationsComponent extends UnsubscribeComponent {

  private locationService = inject(LocationService);
  private alertService = inject(AlertService);
  private store = inject(Store);

  formCtrl: FormControl = new FormControl('');
  allLocations: any = [];

  constructor() {
    super();
  }

  ngOnInit() {
    this.locationService.getLocations().pipe(take(1)).subscribe({
      next: (locations) => {
        this.allLocations = locations.filter((location) => !location.ext.hideInMSSP);
        this.formCtrl.setValue(this.allLocations[0].name);
        this.setLocation();
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
      }
    });
  }

  setLocation() {
    this.store.dispatch(setLocation({ location: this.allLocations.find((location) => location.name === this.formCtrl.value).number }));
  }

}

@if(allLocations.length){
<div fxLayout="column" fxFlex="100" fxLayoutAlign="center center">
    <mat-form-field appearance="outline" class="p-0">
        <mat-label>Property Name</mat-label>
        <div fxLayout="row" fxLayoutAlign="start center">
            <span class="material-symbols-outlined distance-icon">distance</span>
            <mat-select [formControl]="formCtrl" (selectionChange)="setLocation()">
                @for(option of allLocations; track option){
                <mat-option [value]="option.name">
                    {{(option.ext.operator && option.ext.operator !== 'PlayNow')? option.ext.operator + ' - ' :
                    ''}}{{option.name}}
                </mat-option>
                }
            </mat-select>
        </div>
    </mat-form-field>
</div>
}
