// src/app/components/product/product.component.ts
import { Component, Input, OnInit, inject } from '@angular/core';
import { Store } from '@ngrx/store';
import { addItem, removeItem } from '../../states/actions/cart.action';
import { FlexLayoutModule } from '@angular/flex-layout';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { AlertService } from '../../services/alert/alert.service';
import { MatIconModule } from '@angular/material/icon';
import { Subscription } from 'rxjs';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectChange, MatSelectModule } from '@angular/material/select';
import { UnsubscribeComponent } from '../common/unsubscribe/unsubscribe.component';
import { StandardCurrencyPipe } from "../../pipes/standard-currency/standard-currency.pipe";
import { Router } from '@angular/router';

@Component({
  selector: 'app-product',
  standalone: true,
  imports: [FlexLayoutModule, CommonModule, MatButtonModule, MatIconModule, MatFormFieldModule, MatSelectModule, StandardCurrencyPipe],
  templateUrl: './product.component.html',
  styleUrl: './product.component.scss'
})
export class ProductComponent extends UnsubscribeComponent implements OnInit {
  private store = inject(Store);
  private router = inject(Router);
  readonly hemming = 'Hemming';
  @Input() product;
  cartItems: any[] = [];
  quantity: number = 1;

  constructor(private alertService: AlertService) {
    super();
    this.subscriptions.push(
      this.store.select('cart').subscribe((cart) => {
        this.cartItems = cart.items;
        if (this.product?.sku && this.isInCart()) {
          this.quantity = this.cartItems.find(x => x.sku === this.product.sku).quantity
        }else{
          this.quantity = 1;
        }
      })
    )
  }

  ngOnInit() {
    this.subscriptions.push(
      this.store.select('cart').subscribe((cart) => {
        this.cartItems = cart.items;
        if (this.product?.sku && this.isInCart() ) {
          this.quantity = this.cartItems.find(x => x.sku === this.product.sku).quantity
        }else{
          this.quantity = 1;
        }
      })
    )
  }


  addToCart() {
    this.store.dispatch(addItem({ item: {...this.product, quantity: this.quantity} }));
    this.alertService.successAlert(`Item successfully added to your cart.`, 'Go to Cart')
    .onAction()
    .subscribe(() => this.router.navigate(['checkout']));
  }

  removeFromCart() {
    this.quantity = 1;
    this.store.dispatch(removeItem({ itemId: this.product.sku }));
    this.alertService.successAlert(`Item successfully removed from your cart.`, 'Go to Cart')
    .onAction()
    .subscribe(() => this.router.navigate(['checkout']));
  }

  isInCart(): boolean {
    return !!this.cartItems.find(x => x.sku === this.product.sku)
  }

  onSelectionChange(event: MatSelectChange, product) {
    product.quantity = event.value;
    this.store.dispatch(addItem({ item: { ...this.product, quantity: this.quantity } }))
  }

}

<div fxFlex="1 1 auto" fxLayout="column" fxLayoutAlign="start start" class="card" [ngClass]="{'hemming-card': product.category === hemming}">
  @if(product.category === hemming){

    <img class="hemming" [src]="product.url" [alt]="product.name" loading="lazy">
  }@else{

    <img class="img" [src]="product.url" [alt]="product.name" loading="lazy">
  }
  <p class="fw-b mt-5 mb-5">{{product.name}}</p>
  <div class="w-100p" fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="10px">
    <div fxLayout="row" fxLayoutAlign="start center">
      <p class="fw-b m-0 mr-5">Qty:</p>
    <mat-form-field appearance="outline" class="w-80">
      <mat-select [(value)]="quantity" (selectionChange)="onSelectionChange($event, product)">
        @for(quantity of [1, 2,3,4,5,6,7,8,9,10]; track quantity){
        <mat-option [value]="quantity">{{quantity}}</mat-option>
        }
      </mat-select>
    </mat-form-field>
    
    </div>
    <p>{{product.cost| standardCurrency}}</p>
  </div>
  <!-- <p class="description mt-5">{{product.desc}}</p> -->
  @if(product.ext?.nonReturnable){
  <small class="red-label mt-10 mb-10">Non Returnable</small>
  }
  @if(!isInCart()){
  <button class="button w-100p h-40 mb-10" mat-flat-button color="primary" type="button" (click)="addToCart()">
    <!-- <mat-icon>shopping_bag</mat-icon> -->
    Add to Bag</button>
  } @else{
  <button class="button w-100p h-40 mb-10 stroked-btn" mat-stroked-button color="primary" type="button"
    (click)="removeFromCart()">
    <!-- <mat-icon>shopping_bag</mat-icon> -->
    Remove from Bag</button>
  }
</div>

// react/src/components/Product/Product.tsx
import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { addItem, removeItem } from '../../store/actions/cartActions';
import { useAlert } from '../../services/alert/alertService';
import { formatCurrency } from '../../utils/formatCurrency';

interface ProductProps {
  product: {
    sku: string;
    name: string;
    cost: number;
    url: string;
    category: string;
    ext?: {
      nonReturnable?: boolean;
    };
  };
}

const Card = styled.div<{ isHemming: boolean }>`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  height: ${props => props.isHemming ? '300px' : '530px'};
  padding: 16px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
`;

const ProductImage = styled.img<{ isHemming: boolean }>`
  width: ${props => props.isHemming ? '100%' : 'auto'};
  max-width: 300px;
  height: auto;
  aspect-ratio: ${props => props.isHemming ? 'auto' : '5 / 6'};
  object-fit: cover;
`;

const ProductName = styled.p`
  font-weight: bold;
  margin: 20px 0;
`;

const QuantityContainer = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  margin-bottom: 16px;
`;

const QuantitySelect = styled.select`
  width: 80px;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
`;

const Price = styled.p`
  font-weight: bold;
`;

const NonReturnableLabel = styled.small`
  color: red;
  margin: 10px 0;
  display: block;
`;

const Button = styled.button<{ isInCart: boolean }>`
  margin-top: auto;
  width: 100%;
  height: 40px;
  border-radius: 5px;
  border: ${props => props.isInCart ? '2px solid var(--primary)' : 'none'};
  background-color: ${props => props.isInCart ? 'transparent' : 'var(--primary)'};
  color: ${props => props.isInCart ? 'var(--primary)' : 'white'};
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    opacity: 0.9;
  }
`;

export function Product() {
    const dispatch = useDispatch();
    //   const navigate = useNavigate();
    //   const { showSuccess } = useAlert();
    //   const [quantity, setQuantity] = useState(1);
    //   const cartItems = useSelector((state: any) => state.cart.items);
    //   const isInCart = cartItems.some((item: any) => item.sku === product.sku);
    //   useEffect(() => {
    //     if (isInCart) {
    //       const cartItem = cartItems.find((item: any) => item.sku === product.sku);
    //       setQuantity(cartItem.quantity);
    //     } else {
    //       setQuantity(1);
    //     }
    //   }, [isInCart, cartItems, product.sku]);
    //   const handleQuantityChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    //     const newQuantity = parseInt(e.target.value);
    //     setQuantity(newQuantity);
    //     dispatch(addItem({ ...product, quantity: newQuantity }));
    //   };
    //   const handleAddToCart = () => {
    //     dispatch(addItem({ ...product, quantity }));
    //     showSuccess('Item successfully added to your cart.');
    //     navigate('/checkout');
    //   };
    //   const handleRemoveFromCart = () => {
    //     setQuantity(1);
    //     dispatch(removeItem(product.sku));
    //     showSuccess('Item successfully removed from your cart.');
    //     navigate('/checkout');
    //   };
    //   return (
    //     <Card isHemming={product.category === 'Hemming'}>
    //       <ProductImage
    //         src={product.url}
    //         alt={product.name}
    //         loading="lazy"
    //         isHemming={product.category === 'Hemming'}
    //       />
    //       <ProductName>{product.name}</ProductName>
    //       <QuantityContainer>
    //         <div>
    //           <span style={{ fontWeight: 'bold', marginRight: '5px' }}>Qty:</span>
    //           <QuantitySelect value={quantity} onChange={handleQuantityChange}>
    //             {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((qty) => (
    //               <option key={qty} value={qty}>
    //                 {qty}
    //               </option>
    //             ))}
    //           </QuantitySelect>
    //         </div>
    //         <Price>{formatCurrency(product.cost)}</Price>
    //       </QuantityContainer>
    //       {product.ext?.nonReturnable && (
    //         <NonReturnableLabel>Non Returnable</NonReturnableLabel>
    //       )}
    //       <Button
    //         isInCart={isInCart}
    //         onClick={isInCart ? handleRemoveFromCart : handleAddToCart}
    //       >
    //         {isInCart ? 'Remove from Bag' : 'Add to Bag'}
    //       </Button>
    //     </Card>
    //   );
}
