// react/src/components/Login/Login.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAlert } from '../../services/alert/alertService';
import { useLogin } from '../../services/login/loginService';

const Container = styled.div`
  display: flex;
  background-color: white;
  width: 100%;
`;

const LeftColumn = styled.div`
  flex: 70%;
  display: flex;
  flex-direction: column;
  align-items: flex-end;
`;

const RightColumn = styled.div`
  flex: 30%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
`;

const LogoContainer = styled.div`
  display: flex;
  justify-content: center;
  margin: 100px 0 50px;
`;

const Logo = styled.img`
  width: 250px;
`;

const FormContainer = styled.div`
  width: 100%;
  display: flex;
  justify-content: center;
`;

const Form = styled.form`
  width: 80%;
  display: flex;
  flex-direction: column;
  gap: 20px;
`;

const Input = styled.input`
  width: 100%;
  padding: 12px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  font-size: 16px;
  &:focus {
    outline: none;
    border-color: #1976d2;
  }
`;

const Button = styled.button<{ primary?: boolean; stroked?: boolean }>`
  padding: 25px;
  margin: 10px 0;
  border: ${props => props.stroked ? '1px solid #1976d2' : 'none'};
  background-color: ${props => props.primary ? '#1976d2' : 'transparent'};
  color: ${props => props.primary ? 'white' : '#1976d2'};
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
`;

const ProgressBar = styled.div`
  width: 100%;
  height: 4px;
  background-color: #e0e0e0;
  position: relative;
  overflow: hidden;

  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #1976d2;
    animation: progress 2s infinite;
  }

  @keyframes progress {
    0% {
      transform: translateX(-100%);
    }
    100% {
      transform: translateX(100%);
    }
  }
`;

const DividerContainer = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 10px;
  margin: 10px 0;
`;

const Divider = styled.div`
  flex: 1;
  height: 1px;
  background-color: #e0e0e0;
`;

const DividerText = styled.p`
  color: #666;
  margin: 0;
`;

interface FormData {
  username: string;
  password: string;
}

export const Login: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { showError } = useAlert();
  const { login } = useLogin();
  const [formData, setFormData] = useState<FormData>({
    username: '',
    password: ''
  });
  const [showLoginProgress, setShowLoginProgress] = useState(false);
  const [isFormValid, setIsFormValid] = useState(false);

  useEffect(() => {
    const searchParams = new URLSearchParams(location.search);
    const email = searchParams.get('email');
    if (email) {
      setFormData(prev => ({
        ...prev,
        username: atob(email)
      }));
    }
  }, [location]);

  useEffect(() => {
    const isValid = formData.username && formData.password;
    setIsFormValid(!!isValid);
  }, [formData]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setShowLoginProgress(true);

    try {
      const response = await login(formData.username, formData.password);
      if (response.token) {
        localStorage.setItem('accessToken', response.token);
        navigate('/dashboard');
      }
    } catch (error: any) {
      showError(error?.error?.error || error?.message);
      setShowLoginProgress(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  return (
    <Container>
      <LeftColumn />
      <RightColumn>
        <LogoContainer>
          <Logo src="/assets/logo-login.svg" alt="Logo" />
        </LogoContainer>
        <FormContainer>
          <Form onSubmit={handleSubmit}>
            <Input
              type="email"
              name="username"
              placeholder="Email"
              value={formData.username}
              onChange={handleChange}
              required
            />
            <Input
              type="password"
              name="password"
              placeholder="Password"
              value={formData.password}
              onChange={handleChange}
              required
            />
            <Button type="submit" primary disabled={!isFormValid || showLoginProgress}>
              SIGN IN
            </Button>
            {showLoginProgress && <ProgressBar />}
          </Form>
        </FormContainer>
        <DividerContainer>
          <Divider />
          <DividerText>Not a Member ?</DividerText>
          <Divider />
        </DividerContainer>
        <Button stroked onClick={() => navigate('/enroll')}>
          CREATE AN ACCOUNT
        </Button>
      </RightColumn>
    </Container>
  );
};

// src/app/components/login/login.component.ts
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatButtonModule } from '@angular/material/button';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { AlertService } from '../../services/alert/alert.service';
import { LoginService } from '../../services/login/login.service';
import { MemberInfo } from '../../models/member-info';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatCardModule } from '@angular/material/card';
import { filter, Subscription } from 'rxjs';
import { MatDividerModule } from '@angular/material/divider';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    FlexLayoutModule,
    MatCheckboxModule,
    MatButtonModule,
    ReactiveFormsModule,
    FormsModule,
    MatInputModule,
    MatFormFieldModule,
    RouterModule,
    MatProgressBarModule,
    MatCardModule,
    MatDividerModule
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  // route = inject(ActivatedRoute);
  // showLoginProgress: boolean = false;
  // loginForm: FormGroup = this.fb.group({});
  // private queryParamSub: Subscription | undefined;

  // constructor(private fb: FormBuilder, private loginService: LoginService, private router: Router, private alert: AlertService) { }

  // ngOnInit(): void {
  //   localStorage.clear();
  //   this.loginForm = this.fb.group({
  //     username: ['', [Validators.required, Validators.email]],
  //     password: ['', [Validators.required]]
  //   });
  //   this.queryParamSub = this.route.queryParamMap.pipe(
  //     filter(params => params.has('email'))
  //   ).subscribe(params => {
  //     this.loginForm.get(['username'])?.setValue(atob(params.get('email') || ''));
  //   });
  // }

  // onSubmit() {
  //   this.showLoginProgress = true;
  //   this.loginForm.disable();
  //   this.loginService
  //     .login(this.loginForm.value)
  //     .subscribe({
  //       next: (res: MemberInfo) => {
  //         localStorage.setItem('accessToken', res.accessToken);
  //         localStorage.setItem('idToken', res.idToken);
  //         localStorage.setItem('refreshToken', res.refreshToken);
  //         this.router.navigate(['/dashboard']);
  //       },
  //       error: (error) => {
  //         this.alert.errorAlert(error?.error?.error || error?.message);
  //         this.showLoginProgress = false;
  //         this.loginForm.enable();
  //       },
  //     })
  // }

  // ngOnDestroy(): void {
  //   if (this.queryParamSub) {
  //     this.queryParamSub.unsubscribe();
  //   }
  // }
}

<!-- <div fxFlex class="container bg-white" fxLayout="row" fxLayoutAlign="start">
    <div fxFlex="70" fxLayout="column" class="left-column" fxLayoutAlign="end start"></div>
    <div fxFlex="30" fxLayout="column" fxLayoutAlign="center center">
        <div fxLayout="row" fxLayoutAlign="center" class="mt-100 mb-50">
            <img src="/assets/logo-login.svg" alt="Logo" width="250">
        </div>
        <div fxLayout="row" fxLayoutAlign="center start" fxFlex="100" class="w-100p">
            <div fxLayout="column" fxLayoutAlign="center" class="w-80p">
                <form [formGroup]="loginForm" fxLayout="column" fxLayoutAlign="center" fxLayoutGap="20px"
                    (ngSubmit)="onSubmit()" class="login-form">
                    <mat-form-field appearance="outline">
                        <mat-label>Email</mat-label>
                        <input formControlName="username" matInput type="email" id="email">
                        <mat-error>Email is requried!</mat-error>
                    </mat-form-field>
                    <mat-form-field appearance="outline">
                        <mat-label>Password</mat-label>
                        <input formControlName="password" matInput type="password" id="password">
                        <mat-error>Password is requried!</mat-error>
                    </mat-form-field>
                    <button [disabled]="loginForm.disabled || !loginForm.valid" mat-flat-button color="primary"
                        type="submit" class="signin-btn mt-10 mb-10 p-25">SIGN IN</button>
                    @if (showLoginProgress) {
                        <mat-progress-bar mode="indeterminate"></mat-progress-bar>
                    }
                </form>
                <div fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="10" class="mt-10 mb-10">
                    <mat-divider class="w-25p"></mat-divider>
                    <p class="color-gray">Not a Member ?</p>
                    <mat-divider class="w-25p"></mat-divider>
                </div>
                <button mat-stroked-button color="accent" [routerLink]="'/enroll'" class="mt-10 mb-10 p-25 stroked-btn">CREATE AN ACCOUNT</button>
                <div fxLayout="column" fxLayoutAlign="center center" class="mt-60">
                </div>
            </div>
        </div>
    </div>
</div> -->
