// react/src/components/ClippableCoupons/ClippableCoupons.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useSelector } from 'react-redux';
import { useSegment } from '../../services/segment/segmentService';
import { useAlert } from '../../services/alert/alertService';
import { CardMiniSkeleton } from '../common/CardMiniSkeleton/CardMiniSkeleton';
import { NoData } from '../common/NoData/NoData';
import { RootState } from '../../store/reducers';

interface Segment {
  _id: string;
  name: string;
  description: string;
}

interface MemberSegment {
  _id: string;
  segment: string;
}

interface CouponButtonProps {
  claimed: boolean;
}

export const ClippableCoupons: React.FC = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [segments, setSegments] = useState<Segment[]>([]);
  const [memberSegments, setMemberSegments] = useState<MemberSegment[]>([]);
  
  const memberInfo = useSelector((state: RootState) => state.member.member);
  const { getAllSegments, getMemberSegments, addMemberSegment, deleteMemberSegment } = useSegment();
  // const { successAlert, errorAlert } = useAlert();

  useEffect(() => {
    if (memberInfo) {
      getSegments();
    }
  }, [memberInfo]);

  const getSegments = async () => {
    try {
      setIsLoading(true);
      const segmentsData = await getAllSegments(JSON.stringify({ "ext.marketing": true }));
      setSegments(segmentsData);
      
      const memberSegmentsData = await getMemberSegments(5, getQuery());
      setMemberSegments(memberSegmentsData);
    } catch (error: any) {
      // errorAlert(error?.error?.error || error?.message);
    } finally {
      setIsLoading(false);
    }
  };

  const getQuery = () => {
    return JSON.stringify({
      member: memberInfo?._id,
      segment: { $in: segments.map((segment) => segment._id) }
    });
  };

  const isClaimed = (segmentId: string) => 
    !!memberSegments.find(x => x.segment === segmentId);

  const updateSegment = async (segmentId: string) => {
    try {
      const existingSegmentIndex = memberSegments.findIndex(x => x.segment === segmentId);
      
      if (existingSegmentIndex > -1) {
        await deleteMemberSegment(memberSegments[existingSegmentIndex]._id);
        const updatedSegments = [...memberSegments];
        updatedSegments.splice(existingSegmentIndex, 1);
        setMemberSegments(updatedSegments);
        // successAlert('Coupon has been successfully deactivated.');
      } else {
        const newSegment = await addMemberSegment(memberInfo?._id || '', segmentId);
        setMemberSegments([...memberSegments, newSegment]);
        // successAlert('Coupon has been successfully activated.');
      }
    } catch (error: any) {
      // errorAlert(error?.error?.error || error?.message);
    }
  };

  if (isLoading) {
    return <CardMiniSkeleton />;
  }

  // if (!segments.length) {
  //   return <NoData message="No coupons available" />;
  // }

  return (
    <Container>
      {segments.map((segment) => (
        <CouponCard key={segment._id}>
          <CouponContent>
            <CouponTitle>{segment.name}</CouponTitle>
            <CouponDescription>{segment.description}</CouponDescription>
            <CouponButton 
              onClick={() => updateSegment(segment._id)}
              claimed={isClaimed(segment._id)}
            >
              {isClaimed(segment._id) ? 'Deactivate' : 'Activate'}
            </CouponButton>
          </CouponContent>
        </CouponCard>
      ))}
    </Container>
  );
};

const Container = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
  padding: 20px;
`;

const CouponCard = styled.div`
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 20px;
`;

const CouponContent = styled.div`
  display: flex;
  flex-direction: column;
  gap: 10px;
`;

const CouponTitle = styled.h3`
  margin: 0;
  font-size: 18px;
  color: var(--text-color);
`;

const CouponDescription = styled.p`
  margin: 0;
  color: var(--text-secondary);
  font-size: 14px;
`;

const CouponButton = styled.button<CouponButtonProps>`
  padding: 8px 16px;
  border: none;
  border-radius: 4px;
  background-color: ${(props: CouponButtonProps) => props.claimed ? 'var(--error-color)' : 'var(--primary-color)'};
  color: white;
  cursor: pointer;
  font-weight: 500;
  transition: background-color 0.2s;

  &:hover {
    background-color: ${(props: CouponButtonProps) => props.claimed ? 'var(--error-hover)' : 'var(--primary-hover)'};
  }
`;

// src/app/components/clippable-coupons/clippable-coupons.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnDestroy, inject } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { Store } from '@ngrx/store';
import { Subscription, switchMap } from 'rxjs';
import { Segment } from '../../models/segment';
import { AlertService } from '../../services/alert/alert.service';
import { SegmentService } from '../../services/segment/segment.service';
import { CardMiniSkeletonComponent } from "../card-mini-skeleton/card-mini-skeleton.component";
import { NoDataComponent } from "../common/no-data/no-data.component";

@Component({
  selector: 'app-clippable-coupons',
  standalone: true,
  imports: [ReactiveFormsModule, MatCardModule, MatButtonModule, FlexLayoutModule, CommonModule, CardMiniSkeletonComponent, NoDataComponent],
  templateUrl: './clippable-coupons.component.html',
  styleUrl: './clippable-coupons.component.scss'
})
export class ClippableCouponsComponent implements OnDestroy {
  store = inject(Store);
  memberInfo: any;
  segmentFormCtrl: FormControl = new FormControl(null, [Validators.required]);
  subscriptions: Subscription[] = [];
  segments: any = [];
  memberSegments: any = [];
  isLoading: boolean = true;



  constructor(private segmentService: SegmentService, private alertService: AlertService) { }

  ngOnInit(): void {
    this.subscriptions.push(
      this.store.select('member').subscribe({
        next: (member) => {
          this.isLoading = true;
          this.memberInfo = member;
          this.getSegments();
        },
        error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
        }
      })
    )
  }

  getSegments() {
    this.isLoading = true;

    this.segmentService.getAllSegments(JSON.stringify({ "ext.marketing": true }))
      .pipe(
        switchMap((res: Segment[]) => {
          this.segments = res;
          return this.segmentService.getMemberSegments(5, this.getQuery());
        })
      )
      .subscribe({
        next: (memberRes: any) => {
          this.memberSegments = memberRes;
          this.isLoading = false;
        },
        error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
          this.isLoading = false;
        }
      });
  }


  getQuery() {
    return JSON.stringify({
      member: this.memberInfo._id,
      segment: { $in: this.segments.map((segment) => segment._id) }
    })
  }

  isClaimed = (segmentId: string) => !!this.memberSegments.find(x => x.segment === segmentId);

  updateSegment(segmentId: string) {
    const existingSegment = this.memberSegments.findIndex(x => x.segment === segmentId)
    if (existingSegment > -1) {
      this.segmentService.deleteMemberSegment(this.memberSegments[existingSegment]._id).subscribe({
        next: () => {
          this.memberSegments.splice(existingSegment, 1);
          this.alertService.successAlert('Coupon has been successfully deactivated.')
        },
        error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
        },
      })
    } else {
      this.segmentService.addMemberSegment(this.memberInfo._id, segmentId).subscribe({
        next: (res) => {
          this.memberSegments.push(res);
          this.alertService.successAlert('Coupon has been successfully activated.')
        },
        error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
        },
      })
    }


  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(x => x.unsubscribe());
  }
}

@if(isLoading){
<ng-container *ngTemplateOutlet="Loader"></ng-container>
}@else{
@if(segments.length){
<ng-container *ngTemplateOutlet="Segments"></ng-container>
}@else{
    <app-no-data>No coupons available.</app-no-data>
}
}

<ng-template #Segments>
    <div fxLayout="column" fxLayoutGap="10" class="mt-20">
        <div fxLayout="row" fxLayoutGap="20">
            <div class="m-0" fxFlex fxLayout="row wrap" fxLayoutGap="10px grid">
                @for (segment of segments; track $index) {
                    <div fxFlex="25">
                        <mat-card class="box-shadow-none border-gray bg-white h-300" >
                            <mat-card-content class="h-100p">
                                <div fxLayout="column" fxLayoutAlign="space-between center" fxLayoutGap="10" class="h-100p">
                                    <img src="assets/bclc-logo.png">
                                    <h2 class="m-0 color-accent line-height-adjust">{{segment.name}}</h2>
                                    <p class="color-gray mt-10">{{segment.description}}</p>
                                    <button mat-flat-button class="w-100p" [color]="isClaimed(segment._id) ? 'accent' : 'primary'"
                                        (click)="updateSegment(segment._id)">{{isClaimed(segment._id) ? 'Deactivate' : 'Activate'}}
                                    </button>
                                </div>
                            </mat-card-content>
                        </mat-card>
                    </div>
                }
            </div>
        </div>
    </div>
</ng-template>

<ng-template #Loader>
    <div class="mt-50"> 
        <app-card-mini-skeleton></app-card-mini-skeleton>
    </div>
</ng-template>
