// src/app/components/purchase-history/purchase-history.component.ts
import {
  AfterViewInit,
  Component,
  inject,
  OnDestroy,
  OnInit,
  ViewChild,
} from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatCardModule } from '@angular/material/card';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSortModule } from '@angular/material/sort';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { MemberService } from '../../services/member/member.service';
import { Store } from '@ngrx/store';
import { Member } from '../../models/member';
import { PurchaseHistory } from '../../models/purchase-history';
import { AlertService } from '../../services/alert/alert.service';
import { distinctUntilChanged, Subscription } from 'rxjs';

import { animate, state, style, transition, trigger } from '@angular/animations';

import { MatButtonModule } from '@angular/material/button';
import { MatExpansionModule } from '@angular/material/expansion';
import { StandardCurrencyPipe } from "../../pipes/standard-currency/standard-currency.pipe";
import { NoDataComponent } from "../common/no-data/no-data.component";
import { LOB } from '../../enums/lob-enum';

@Component({
  selector: 'app-purchase-history',
  standalone: true,
  imports: [
    MatTableModule,
    FlexLayoutModule,
    MatCardModule,
    MatChipsModule,
    MatPaginatorModule,
    MatSelectModule,
    MatFormFieldModule,
    CommonModule,
    MatFormFieldModule,
    FormsModule,
    ReactiveFormsModule,
    MatSortModule,
    MatInputModule,
    MatFormFieldModule,
    MatIconModule,
    MatExpansionModule,
    MatButtonModule,
    StandardCurrencyPipe,
    NoDataComponent
  ],
  providers: [DatePipe],
  templateUrl: './purchase-history.component.html',
  animations: [
    trigger('detailExpand', [
      state('collapsed,void', style({ height: '0px', minHeight: '0' })),
      state('expanded', style({ height: '*' })),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
  styleUrl: './purchase-history.component.scss'
})

export class PurchaseHistoryComponent implements OnInit, AfterViewInit, OnDestroy {
  private store = inject(Store);
  private readonly ACTIVITY_TYPE_ACCRUAL = 'Accrual';
  private readonly ACTIVITY_STATUS_PROCESSED = 'Processed';
  private static readonly TAX_SKU = 'Tax';
  private static readonly GRATUITY = 'Gratuity';
  private static readonly DISCOUNT_SKU = 'Discount';

  currentDate: string;
  memberInfo?: Member;

  @ViewChild(MatPaginator) paginator!: MatPaginator;

  displayedColumns: string[] = ['date', 'type', 'bookingId', 'location', 'desc', 'totalSpend', 'total', 'statusPoints', 'rewardEarned', 'expand'];
  dataSource = new MatTableDataSource<PurchaseHistory>();

  skeletonLoader = true;
  purchaseHistory: any[] = [];
  tableData: any[] = [];
  memberPoints: any[] = [];
  pointsLoader = true;
  subscriptions: Subscription[] = [];
  expandedElement: any;

  constructor(private memberService: MemberService, private alertService: AlertService, private datePipe: DatePipe) {
    this.currentDate = this.datePipe.transform(new Date(), 'yyyy-MM-ddTHH:mm:ss.SSS\'Z\'', 'UTC')!;
  }

  ngOnInit() {
    this.subscriptions.push(
      this.store.select('member').pipe(distinctUntilChanged()).subscribe((member: Member) => {
        if (Object.keys(member).length) {
          this.skeletonLoader = true;
          this.dataSource.data = [];
          this.pointsLoader = true;
          this.memberInfo = member;
          this.getActivityHistory();
        }
      }),
    );
  }

  getActivityHistory() {
    this.dataSource.data = [];
    this.skeletonLoader = true;
    this.pointsLoader = true;
    this.subscriptions.push(
      this.memberService.getActivityHistory(this.memberInfo?._id ?? '').subscribe({
        next: (purchaseHistory) => {
          this.purchaseHistory = purchaseHistory.filter((history) => history.status === this.ACTIVITY_STATUS_PROCESSED);
          this.purchaseHistory.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
          this.prepareTableData();
          this.skeletonLoader = false;
        }, error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
          this.skeletonLoader = false;
        }
      })
    )
  }

  getOffers(lineItems: any, type: string) {
    const discountItems = lineItems.filter((item: any) => item.type === type);
    const uniqueItems: Set<string> = new Set(discountItems.map((item) => item.itemSKU));
    return Array.from(uniqueItems).map((uniq) => ({
      key: uniq, value: discountItems.filter((item) => item.itemSKU === uniq).reduce((a, v) => a + v.itemAmount, 0)
    }))
  }

  getTotal(lineItems: any, type: string = '') {
    return lineItems.filter((item: any) => !type || (type && item.type === type)).reduce((acc, val) => acc + val.itemAmount, 0)
  }

  formatHistory = (history) => {
    const pointsValue = this.getTotalPurse(history.result?.data?.purses);
    return {
      date: history.date,
      bookingId: history?.ext?.folioId ? history.ext.folioId : '-',
      location: history?.location?.name ?? '-',
      desc: history.result?.data?.desc ?? '-',
      total: this.getPurseValue(history.result?.data?.purses, 'Status Points'),
      serviceStatusPoints: this.getPurseValue(history.result?.data?.purses, 'GCGC Status Points'),
      rewardUsed: pointsValue < 0 ? Math.abs(pointsValue) : 0,
      spend: history.value,
      basePoints: pointsValue,
      lob: history?.ext?.lob,
      type: history.type,
      value: history.value,
      id: history._id,
      isExpandable: history.type === this.ACTIVITY_TYPE_ACCRUAL,
      expanded: false,
      gaming: (history?.ext?.gaming),
      lineItems: history.lineItems.map((item: any) => ({ ...item, lob: history?.ext?.lob })),
      summary: {}
    }
  }

  prepareTableData() {
    this.tableData = this.purchaseHistory.map(this.formatHistory)
    this.tableData.forEach((data) => { data.nestedData = this.getNestedData(data.lineItems), data.summary = this.getSummary(data.nestedData) });
    this.dataSource = new MatTableDataSource(this.tableData);
    this.dataSource.paginator = this.paginator;
  }
  getPurseValue(purses: any, type: string) {
    const selectedPurse = purses?.find((purse: any) => purse.name === type);
    if (selectedPurse) {
      return selectedPurse?.new - selectedPurse?.prev;
    }
    return 0;
  }

  getTotalPurse(purses: any, isStatus: boolean = false) {
    const selectedPurse = purses?.filter((purse: any) => isStatus ? purse.name.includes('Status') : !purse.name.includes('Status'));
    if (selectedPurse?.length) {
      return selectedPurse.reduce((acc, purse) => (purse.new - purse.prev) + acc, 0);
    }
    return 0;
  }

  getNestedData(lineItems: any) {
    const nestedData: any = [];
    for (const key of Object.keys(LOB)) {
      const filteredItems = lineItems.filter((lineItem) => lineItem?.lob?.toUpperCase() === key);
      if (filteredItems.length) {
        nestedData.push({
          title: LOB[key],
          subTotal: { key: 'Subtotal', value: this.getTotal(filteredItems, 'Normal') },
          offers: this.getOffers(filteredItems, PurchaseHistoryComponent.DISCOUNT_SKU),
          tax: { key: PurchaseHistoryComponent.TAX_SKU, value: this.getTotal(filteredItems, PurchaseHistoryComponent.TAX_SKU) },
          gratuity: { key: PurchaseHistoryComponent.GRATUITY, value: this.getTotal(filteredItems, PurchaseHistoryComponent.GRATUITY) },
          total: { key: 'Total ' + LOB[key], value: this.getTotal(filteredItems) }
        })
      }
    }
    return nestedData;
  }

  getSummary(nestedData) {
    if (nestedData.length) {
      const summaryData = nestedData.map((data) => ({ key: data.title, value: data.total.value }));
      summaryData.push({ key: 'Total Charges', value: summaryData.reduce((acc, v) => acc + v.value, 0) })
      return summaryData;
    }
  }

  getSign = (val) => (val > 0) ? '+' : '';

  ngAfterViewInit() {
    if (this.paginator) {
      this.dataSource.paginator = this.paginator;
      this.paginator._intl.itemsPerPageLabel = "Rows per page";
    }
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(x => x.unsubscribe())
  }
}

<div fxLayout="column" fxLayoutAlign="center center">
    <div fxLayout="column" class="w-1300 mt-20" fxLayoutGap="20">
        <div fxLayout="row" fxLayoutAlign="center center">
            <mat-card class="border-gray w-100p">
                <mat-card-content class="pt-20">
                    <div fxLayout="row" fxLayoutAlign="space-between end" fxLayoutGap="30"
                        class="points-header pl-15 pr-15">
                        <div fxLayout="row" fxLayoutAlig="start center">
                            <h3 class="mt-13 mr-10 font-size-medium">Activity History</h3>
                            <button mat-icon-button class="refresh-btn" (click)="getActivityHistory()">
                                <mat-icon>refresh</mat-icon>
                            </button>
                        </div>
                        <div>
                            <mat-form-field>
                                <input color="primary" matInput (keyup)="applyFilter($event)" placeholder="Search" />
                                <mat-icon color="accent" matSuffix>search</mat-icon>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="ph-table overflow-y-auto">
                        <mat-accordion>
                            <table mat-table [dataSource]="dataSource" multiTemplateDataRows>
                                <ng-container matColumnDef="index">
                                    <th mat-header-cell *matHeaderCellDef>#</th>
                                    <td mat-cell *matCellDef="let element;">{{ element.index }}</td>
                                </ng-container>

                                <ng-container matColumnDef="date">
                                    <th mat-header-cell *matHeaderCellDef>Date</th>
                                    <td mat-cell *matCellDef="let element">{{ element.date | date }}</td>
                                </ng-container>

                                <!-- Type Column -->
                                <ng-container matColumnDef="type">
                                    <th mat-header-cell *matHeaderCellDef>Activity</th>
                                    <td mat-cell *matCellDef="let element">{{ element.type }}</td>
                                </ng-container>

                                <!-- Booking ID Column -->
                                <ng-container matColumnDef="bookingId">
                                    <th mat-header-cell *matHeaderCellDef>Folio #</th>
                                    <td mat-cell *matCellDef="let element">{{ element.bookingId }}</td>
                                </ng-container>

                                <!-- Location Type Column -->
                                <ng-container matColumnDef="location">
                                    <th mat-header-cell *matHeaderCellDef>Location</th>
                                    <td mat-cell *matCellDef="let element">{{ element.location }}</td>
                                </ng-container>

                                <!-- Description Column -->
                                <ng-container matColumnDef="desc">
                                    <th mat-header-cell *matHeaderCellDef>Details</th>
                                    <td mat-cell *matCellDef="let element">{{ element.gaming ? 'Gaming' : element.desc
                                        }}
                                    </td>
                                </ng-container>

                                <!-- Total Spend -->
                                <ng-container matColumnDef="totalSpend">
                                    <th mat-header-cell *matHeaderCellDef>Total Spend</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight">
                                            {{ element.spend ? (element.spend | standardCurrency) : '-'}}
                                        </div>
                                    </td>
                                </ng-container>

                                <!-- Total Column -->
                                <ng-container matColumnDef="total">
                                    <th mat-header-cell *matHeaderCellDef>Status Points</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight"
                                            [ngClass]="{'earns': element.total > 0,  'spends': element.total < 0, 'no-transactions': element.total === 0}">
                                            {{ element.total ? (element.total | number: '1.0-0') : '-'}}
                                        </div>
                                    </td>
                                </ng-container>

                                <!-- Provider Status Column -->
                                <ng-container matColumnDef="statusPoints">
                                    <th mat-header-cell *matHeaderCellDef>SP Status Points</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight"
                                            [ngClass]="{'earns': element.serviceStatusPoints > 0,  'spends': element.serviceStatusPoints < 0, 'no-transactions': element.serviceStatusPoints === 0}">
                                            {{ element.serviceStatusPoints ? (element.serviceStatusPoints | number: '1.0-0') : '-'}}
                                        </div>
                                    </td>
                                </ng-container>


                                <ng-container matColumnDef="rewardEarned">
                                    <th mat-header-cell *matHeaderCellDef>Points</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight"
                                            [ngClass]="{'earns': element.basePoints > 0,  'spends': element.basePoints < 0, 'no-transactions': element.basePoints === 0}">
                                            {{element.basePoints ? (element.basePoints | number: '1.0-0' ) : '-' }}
                                        </div>

                                    </td>
                                </ng-container>

                                <!-- <ng-container matColumnDef="rewardUsed">
                                    <th mat-header-cell *matHeaderCellDef>Points Used</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight"
                                            [ngClass]="{'earns': element.rewardUsed < 0,  'spends': element.rewardUsed > 0, 'no-transactions': element.rewardUsed === 0}">
                                            {{ element.rewardUsed ? (element.rewardUsed | number: '1.0-0') :'-' }}
                                        </div>
                                    </td>
                                </ng-container> -->

                                <!-- Points Column -->
                                <ng-container matColumnDef="points">
                                    <th mat-header-cell *matHeaderCellDef>Points</th>
                                    <td mat-cell *matCellDef="let element">
                                        <div class="p-5 highlight"
                                            [ngClass]="{'earns': element.points > 0, 'spends': element.points < 0, 'no-transactions': element.points === 0}">
                                            {{getSign(element.points)}}{{ element.points ? (element.points | number :
                                            '1.0-0') :'-' }}
                                        </div>
                                    </td>
                                </ng-container>

                                <ng-container matColumnDef="expand">
                                    <th mat-header-cell *matHeaderCellDef aria-label="row actions">&nbsp;</th>
                                    <td mat-cell *matCellDef="let element">
                                        @if(element.isExpandable){
                                        <button mat-icon-button aria-label="expand row"
                                            (click)="(expandedElement = expandedElement === element ? null : element); $event.stopPropagation()">
                                            @if (expandedElement === element) {
                                            <mat-icon>keyboard_arrow_up</mat-icon>
                                            } @else {
                                            <mat-icon>keyboard_arrow_down</mat-icon>
                                            }
                                        </button>
                                        }

                                    </td>
                                </ng-container>

                                <ng-container matColumnDef="expandedDetail">
                                    <td mat-cell *matCellDef="let element" [attr.colspan]="displayedColumns.length +1"
                                        class="p-0">
                                        <div [@detailExpand]="element == expandedElement ? 'expanded' : 'collapsed'">
                                            <div fxFlex="100" fxLayout="row" fxLayoutAlign="space-around start"
                                                fxLayoutGap="20px">
                                                <div fxFlex="50" class="m-30 w-50p">
                                                    @if (element.nestedData?.length) {
                                                    @for(data of element.nestedData; track $index){
                                                    <div>
                                                        <h4>{{ data.title }}</h4>
                                                        <div fxLayout="column" fxLayoutGap="15">
                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>{{ data.subTotal?.key
                                                                    }}</span>
                                                                <span>{{ data.subTotal?.value |
                                                                    currency }}</span>
                                                            </div>

                                                            @for(offer of data.offers; track $index){
                                                            <div fxLayout="row" fxLayoutAlign="space-between center"
                                                                class="color-green">
                                                                <span>{{ offer.key }}</span>
                                                                <span>{{ offer.value | currency }}</span>
                                                            </div>
                                                            }

                                                            <div fxLayout="row" fxLayoutAlign="space-between center">
                                                                <span>{{ data.tax?.key }}</span>
                                                                <span>{{ data.tax?.value | currency
                                                                    }}</span>
                                                            </div>

                                                            @if(data.gratuity){
                                                            <div fxLayout="row" fxLayoutAlign="space-between center">
                                                                <span>{{ data.gratuity?.key }}</span>
                                                                <span>{{ data.gratuity?.value | currency
                                                                    }}</span>
                                                            </div>
                                                            }

                                                            <div fxLayout="row" fxLayoutAlign="space-between center"
                                                                class="font-size-medium mb-20">
                                                                <span>{{ data.total?.key }}</span>
                                                                <span>{{ data.total?.value |
                                                                    currency }}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    }
                                                    }@else if(element.gaming){
                                                    <div>
                                                        <h4>Casino</h4>
                                                        <div fxLayout="column" fxLayoutGap="15">
                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Cash In</span>
                                                                <span>{{ element.gaming.coinIn | currency }}</span>
                                                            </div>

                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Cash Out</span>
                                                                <span>{{ element.gaming.coinOut | currency }}</span>
                                                            </div>

                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Wager Amount</span>
                                                                <span>{{ element.gaming.wagerAmount | currency }}</span>
                                                            </div>

                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Free Play Credit</span>
                                                                <span>{{ element.gaming.fpCredit | currency
                                                                    }}</span>
                                                            </div>

                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Session Start Time</span>
                                                                <span>{{ element.gaming.sessionStartDate | date : 'MMM
                                                                    d, yyyy h:mm a'
                                                                    }}</span>
                                                            </div>

                                                            <div fxLayout="row" fxLayoutAlign="space-between">
                                                                <span>Session End Time</span>
                                                                <span>{{ element.gaming.sessionEndDate | date : 'MMM d,
                                                                    yyyy h:mm a'
                                                                    }}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    }@else {
                                                    <app-no-data>No transactions found.</app-no-data>
                                                    }
                                                </div>
                                                <div fxFlex="50" class="m-30 w-50p">
                                                    @if (element.summary) {
                                                    <div>
                                                        <h4>Summary</h4>
                                                        <div>
                                                            @for(summary of element.summary; track $index){
                                                            <div fxLayout="row" fxLayoutAlign="space-between center"
                                                                class="font-size-medium mb-20">
                                                                <span class="color-gray">{{ summary.key }}</span>
                                                                <span>{{ summary.value | currency }}</span>
                                                            </div>
                                                            }
                                                        </div>
                                                    </div>
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </ng-container>
                                <tr mat-header-row *matHeaderRowDef="displayedColumns" class="agreement-table-row"></tr>
                                <tr mat-row *matRowDef="let element; columns: displayedColumns;"
                                    class="example-element-row"
                                    [class.example-expanded-row]="expandedElement === element">
                                </tr>
                                <tr mat-row *matRowDef="let row; columns: ['expandedDetail']"
                                    class="example-detail-row"></tr>
                            </table>
                        </mat-accordion>
                        @if(dataSource && (dataSource.data.length === 0 || dataSource.filteredData.length === 0) &&
                        !skeletonLoader){
                        <app-no-data>No data found.</app-no-data>
                        }
                        @if(skeletonLoader){
                        <div class="table-skeleton">
                            <table class="tg">
                                @for (row of [1,2,3,4,5,6,7,8]; track $index){
                                <tr>
                                    @for(line of [1,2,3,4,5,6]; track $index){
                                    <td class="tg-cly1">
                                        <div class="line"></div>
                                    </td>
                                    }
                                </tr>
                                }
                            </table>
                        </div>
                        }
                    </div>
                    <mat-paginator [pageSize]="10" [pageSizeOptions]="[10, 15, 25, 50, 100]"
                        showFirstLastButtons></mat-paginator>
                </mat-card-content>
            </mat-card>
        </div>
    </div>
</div>

// react/src/components/PurchaseHistory/PurchaseHistory.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useDispatch, useSelector } from 'react-redux';
import { useMember } from '../../services/member/memberService';
import { useAlert } from '../../services/alert/alertService';
import { formatCurrency } from '../../utils/formatCurrency';
import { NoData } from '../common/NoData/NoData';
// import { LOB } from '../../enums/lobEnum';

const Container = styled.div`
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
`;

const Table = styled.table`
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
`;

const TableHeader = styled.thead`
  background-color: #f5f5f5;
`;

const TableRow = styled.tr<{ expanded?: boolean }>`
  border-bottom: 1px solid #ddd;
  cursor: ${props => props.expanded ? 'pointer' : 'default'};
  
  &:hover {
    background-color: ${props => props.expanded ? '#f5f5f5' : 'transparent'};
  }
`;

const TableCell = styled.td`
  padding: 12px;
  text-align: left;
`;

const TableHeaderCell = styled.th`
  padding: 12px;
  text-align: left;
  font-weight: bold;
`;

const ExpandButton = styled.button`
  background: none;
  border: none;
  cursor: pointer;
  padding: 8px;
  color: #1976d2;
  
  &:hover {
    color: #1565c0;
  }
`;

const ExpandedContent = styled.div`
  padding: 20px;
  background-color: #f9f9f9;
`;

const SummaryRow = styled.div`
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
  padding: 8px;
  background-color: #f5f5f5;
  border-radius: 4px;
`;

const SearchInput = styled.input`
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  width: 300px;
  margin-bottom: 20px;
`;

const PaginationContainer = styled.div`
  display: flex;
  justify-content: center;
  margin-top: 20px;
  gap: 10px;
`;

const PageButton = styled.button<{ active?: boolean }>`
  padding: 8px 12px;
  border: 1px solid ${props => props.active ? '#1976d2' : '#ddd'};
  background: ${props => props.active ? '#1976d2' : 'white'};
  color: ${props => props.active ? 'white' : '#333'};
  border-radius: 4px;
  cursor: pointer;
  
  &:hover {
    background: ${props => props.active ? '#1565c0' : '#f5f5f5'};
  }
`;

interface PurchaseHistory {
  date: string;
  bookingId: string;
  location: string;
  desc: string;
  total: number;
  serviceStatusPoints: number;
  rewardUsed: number;
  spend: number;
  basePoints: number;
  lob: string;
  type: string;
  value: number;
  id: string;
  isExpandable: boolean;
  expanded: boolean;
  gaming: boolean;
  lineItems: any[];
  nestedData: any[];
  summary: any[];
}

export const PurchaseHistory = () => {
  // const dispatch = useDispatch();
  // const { getActivityHistory } = useMember();
  // const { showError } = useAlert();
  // const member = useSelector((state: any) => state.member);
  
  // const [purchaseHistory, setPurchaseHistory] = useState<PurchaseHistory[]>([]);
  // const [filteredHistory, setFilteredHistory] = useState<PurchaseHistory[]>([]);
  // const [searchTerm, setSearchTerm] = useState('');
  // const [currentPage, setCurrentPage] = useState(1);
  // const [expandedRow, setExpandedRow] = useState<string | null>(null);
  // const [isLoading, setIsLoading] = useState(false);

  // const itemsPerPage = 10;

  // useEffect(() => {
  //   if (member && Object.keys(member).length) {
  //     fetchActivityHistory();
  //   }
  // }, [member]);

  // useEffect(() => {
  //   const filtered = purchaseHistory.filter(history => 
  //     history.bookingId.toLowerCase().includes(searchTerm.toLowerCase()) ||
  //     history.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
  //     history.desc.toLowerCase().includes(searchTerm.toLowerCase())
  //   );
  //   setFilteredHistory(filtered);
  //   setCurrentPage(1);
  // }, [searchTerm, purchaseHistory]);

  // const fetchActivityHistory = async () => {
  //   setIsLoading(true);
  //   try {
  //     const history = await getActivityHistory(member._id);
  //     const processedHistory = history
  //       .filter((h: any) => h.status === 'Processed')
  //       .sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime())
  //       .map(formatHistory);
      
  //     setPurchaseHistory(processedHistory);
  //     setFilteredHistory(processedHistory);
  //   } catch (error: any) {
  //     showError(error?.error?.error || error?.message);
  //   } finally {
  //     setIsLoading(false);
  //   }
  // };

  // const formatHistory = (history: any): PurchaseHistory => {
  //   const pointsValue = getTotalPurse(history.result?.data?.purses);
  //   return {
  //     date: history.date,
  //     bookingId: history?.ext?.folioId || '-',
  //     location: history?.location?.name || '-',
  //     desc: history.result?.data?.desc || '-',
  //     total: getPurseValue(history.result?.data?.purses, 'Status Points'),
  //     serviceStatusPoints: getPurseValue(history.result?.data?.purses, 'GCGC Status Points'),
  //     rewardUsed: pointsValue < 0 ? Math.abs(pointsValue) : 0,
  //     spend: history.value,
  //     basePoints: pointsValue,
  //     lob: history?.ext?.lob,
  //     type: history.type,
  //     value: history.value,
  //     id: history._id,
  //     isExpandable: history.type === 'Accrual',
  //     expanded: false,
  //     gaming: history?.ext?.gaming,
  //     lineItems: history.lineItems.map((item: any) => ({ ...item, lob: history?.ext?.lob })),
  //     nestedData: [],
  //     summary: []
  //   };
  // };

  // const getPurseValue = (purses: any[], type: string) => {
  //   const selectedPurse = purses?.find(purse => purse.name === type);
  //   return selectedPurse ? selectedPurse.new - selectedPurse.prev : 0;
  // };

  // const getTotalPurse = (purses: any[], isStatus: boolean = false) => {
  //   const selectedPurse = purses?.filter(purse => 
  //     isStatus ? purse.name.includes('Status') : !purse.name.includes('Status')
  //   );
  //   return selectedPurse?.length ? 
  //     selectedPurse.reduce((acc, purse) => (purse.new - purse.prev) + acc, 0) : 0;
  // };

  // const getNestedData = (lineItems: any[]) => {
  //   const nestedData: any[] = [];
  //   for (const key of Object.keys(LOB)) {
  //     const filteredItems = lineItems.filter(item => item?.lob?.toUpperCase() === key);
  //     if (filteredItems.length) {
  //       nestedData.push({
  //         title: LOB[key],
  //         subTotal: { key: 'Subtotal', value: getTotal(filteredItems, 'Normal') },
  //         offers: getOffers(filteredItems, 'Discount'),
  //         tax: { key: 'Tax', value: getTotal(filteredItems, 'Tax') },
  //         gratuity: { key: 'Gratuity', value: getTotal(filteredItems, 'Gratuity') },
  //         total: { key: `Total ${LOB[key]}`, value: getTotal(filteredItems) }
  //       });
  //     }
  //   }
  //   return nestedData;
  // };

  // const getTotal = (lineItems: any[], type: string = '') => {
  //   return lineItems
  //     .filter(item => !type || (type && item.type === type))
  //     .reduce((acc, val) => acc + val.itemAmount, 0);
  // };

  // const getOffers = (lineItems: any[], type: string) => {
  //   const discountItems = lineItems.filter(item => item.type === type);
  //   const uniqueItems = new Set(discountItems.map(item => item.itemSKU));
  //   return Array.from(uniqueItems).map(uniq => ({
  //     key: uniq,
  //     value: discountItems
  //       .filter(item => item.itemSKU === uniq)
  //       .reduce((a, v) => a + v.itemAmount, 0)
  //   }));
  // };

  // const getSummary = (nestedData: any[]) => {
  //   if (nestedData.length) {
  //     const summaryData = nestedData.map(data => ({
  //       key: data.title,
  //       value: data.total.value
  //     }));
  //     summaryData.push({
  //       key: 'Total Charges',
  //       value: summaryData.reduce((acc, v) => acc + v.value, 0)
  //     });
  //     return summaryData;
  //   }
  //   return [];
  // };

  // const handleExpand = (id: string) => {
  //   setExpandedRow(expandedRow === id ? null : id);
  // };

  // const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
  //   setSearchTerm(e.target.value);
  // };

  // const totalPages = Math.ceil(filteredHistory.length / itemsPerPage);
  // const paginatedData = filteredHistory.slice(
  //   (currentPage - 1) * itemsPerPage,
  //   currentPage * itemsPerPage
  // );

  // if (isLoading) {
  //   return <Container>Loading...</Container>;
  // }

  // // if (!filteredHistory.length) {
  // //   return <NoData message="No purchase history available" />;
  // // }

  // return (
  //   <Container>
  //     <SearchInput
  //       type="text"
  //       placeholder="Search by booking ID, location, or description"
  //       value={searchTerm}
  //       onChange={handleSearch}
  //     />

  //     <Table>
  //       <TableHeader>
  //         <tr>
  //           <TableHeaderCell>Date</TableHeaderCell>
  //           <TableHeaderCell>Booking ID</TableHeaderCell>
  //           <TableHeaderCell>Location</TableHeaderCell>
  //           <TableHeaderCell>Description</TableHeaderCell>
  //           <TableHeaderCell>Total Spend</TableHeaderCell>
  //           <TableHeaderCell>Status Points</TableHeaderCell>
  //           <TableHeaderCell>Reward Earned</TableHeaderCell>
  //           <TableHeaderCell></TableHeaderCell>
  //         </tr>
  //       </TableHeader>
  //       <tbody>
  //         {paginatedData.map(history => (
  //           <React.Fragment key={history.id}>
  //             <TableRow
  //               expanded={history.isExpandable}
  //               onClick={() => history.isExpandable && handleExpand(history.id)}
  //             >
  //               <TableCell>{new Date(history.date).toLocaleDateString()}</TableCell>
  //               <TableCell>{history.bookingId}</TableCell>
  //               <TableCell>{history.location}</TableCell>
  //               <TableCell>{history.desc}</TableCell>
  //               <TableCell>{formatCurrency(history.spend)}</TableCell>
  //               <TableCell>{history.total}</TableCell>
  //               <TableCell>{history.rewardUsed}</TableCell>
  //               <TableCell>
  //                 {history.isExpandable && (
  //                   <ExpandButton>
  //                     {expandedRow === history.id ? '▼' : '▶'}
  //                   </ExpandButton>
  //                 )}
  //               </TableCell>
  //             </TableRow>
  //             {expandedRow === history.id && (
  //               <tr>
  //                 <TableCell colSpan={8}>
  //                   <ExpandedContent>
  //                     {getNestedData(history.lineItems).map((data, index) => (
  //                       <div key={index}>
  //                         <h3>{data.title}</h3>
  //                         <SummaryRow>
  //                           <span>Subtotal:</span>
  //                           <span>{formatCurrency(data.subTotal.value)}</span>
  //                         </SummaryRow>
  //                         {data.offers.map((offer: any, i: number) => (
  //                           <SummaryRow key={i}>
  //                             <span>{offer.key}:</span>
  //                             <span>{formatCurrency(offer.value)}</span>
  //                           </SummaryRow>
  //                         ))}
  //                         <SummaryRow>
  //                           <span>Tax:</span>
  //                           <span>{formatCurrency(data.tax.value)}</span>
  //                         </SummaryRow>
  //                         <SummaryRow>
  //                           <span>Gratuity:</span>
  //                           <span>{formatCurrency(data.gratuity.value)}</span>
  //                         </SummaryRow>
  //                         <SummaryRow>
  //                           <span>Total:</span>
  //                           <span>{formatCurrency(data.total.value)}</span>
  //                         </SummaryRow>
  //                       </div>
  //                     ))}
  //                   </ExpandedContent>
  //                 </TableCell>
  //               </tr>
  //             )}
  //           </React.Fragment>
  //         ))}
  //       </tbody>
  //     </Table>

  //     <PaginationContainer>
  //       {Array.from({ length: totalPages }, (_, i) => i + 1).map(page => (
  //         <PageButton
  //           key={page}
  //           active={currentPage === page}
  //           onClick={() => setCurrentPage(page)}
  //         >
  //           {page}
  //         </PageButton>
  //       ))}
  //     </PaginationContainer>
  //   </Container>
  // );
};
