// src/app/components/earned-benefits/earned-benefits.component.ts
import { Component, inject } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatCardModule } from '@angular/material/card';
import { CommonModule } from '@angular/common';
import { AlertService } from '../../services/alert/alert.service';
import { CardMiniSkeletonComponent } from "../card-mini-skeleton/card-mini-skeleton.component";
import { State, Store } from '@ngrx/store';
import { NoDataComponent } from "../common/no-data/no-data.component";
import { Member } from '../../models/member';
import { MemberService } from '../../services/member/member.service';
import { ExpiryCheckPipe } from "../../pipes/expiry-check.pipe";
import { Subscription } from 'rxjs';


@Component({
  selector: 'app-earned-benefits',
  standalone: true,
  imports: [
    FlexLayoutModule,
    MatCardModule,
    CommonModule,
    CardMiniSkeletonComponent,
    NoDataComponent,
    MatCardModule,
    ExpiryCheckPipe,
  ],
  templateUrl: './earned-benefits.component.html',
  styleUrl: './earned-benefits.component.scss'
})
export class EarnedBenefitsComponent {
  store = inject(Store);
  state = inject(State);
  alertService = inject(AlertService);
  memberService = inject(MemberService);

  private readonly personalization = 'Personalization';

  isLoading: boolean = true;
  memberBenefits: any = [];
  memberInfo!: Member;
  location: any;
  subscriptions: Subscription[] = [];

  ngOnInit() {
    this.subscriptions.push(
      this.store.select('location').subscribe((location) => {
        this.location = location.location;
        if(this.memberInfo?._id){
          this.getMemberBenefits();
        }
      }),

      this.store.select('member').subscribe({
        next: (member) => {
          this.memberInfo = member;
          if(this.memberInfo?._id){
            this.getMemberBenefits()
          }
        },
        error: (error) => {
          this.alertService.errorAlert(error?.error?.error || error?.message);
        }
      })
    )
  }

  getMemberBenefits() {
    this.memberService.getOffers(this.memberInfo?._id, this.location.number ?? this.location).subscribe({
      next: (offers: any) => {
        this.memberBenefits = offers.filter((offer) => offer.ext?.isBenefit);
        this.isLoading = false;
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
        this.isLoading = false;
      }
    })
  }

  getActivityPayload(locationNum: string) {
    return {
      type: this.personalization,
      date: new Date().toISOString(),
      srcChannelType: 'Web',
      srcChannelID: locationNum,
      couponCode: 'Tier Benefit',
      loyaltyID: this.state.getValue().member.loyaltyId
    };
  }
}

@if(isLoading){
    <ng-container *ngTemplateOutlet="Loader"></ng-container>
    }@else{
    @if(memberBenefits.length){
    <ng-container *ngTemplateOutlet="Offers"></ng-container>
    }@else{
        <app-no-data>No Benefits available.</app-no-data>
    }
    }
    
    <ng-template #Offers>
        <div fxLayout="column" class="mt-20">
            <h3 class="mt-0">Available Member Benefits ({{memberBenefits.length}})</h3>
            <div fxLayout="row" fxLayoutGap="20">
                <div class="m-0" fxFlex fxLayout="row wrap" fxLayoutGap="10px grid">
                    @for (offer of memberBenefits; track $index) {
                    <div fxFlex="50">
                        <mat-card class="box-shadow-none border-gray bg-white">
                            <mat-card-content fxLayout="row" fxLayoutAlign="center center" fxLayoutGap="10" class="h-140">
                                <div class="w-50 img-sec"><img src="assets/bclc-logo.png"></div>
                                <div fxLayout="row" fxLayoutAlign="space-between start" fxFlex="100" class="w-500">
                                    <div fxLayout="column" fxLayoutGap="10" fxFlex="77">
                                        <h3 class="mt-10 card-text-ellipsis">{{ offer.name }}</h3>
                                        <p class="m-0 card-text-ellipsis">{{ offer.desc }}</p>
                                        @if(offer.expirationDate){
                                        <small class="color-gray line-height-adjust card-text-ellipsis">Expires {{ offer.expirationDate | expiryCheck
                                            }}</small>
                                        }
                                    </div>
                                </div>                            
                            </mat-card-content>
                        </mat-card>
                    </div>
                    }
                </div>
            </div>
        </div>
    </ng-template>
    
    
    <ng-template #Loader>
        <div class="mt-50">
            <app-card-mini-skeleton></app-card-mini-skeleton>
        </div>
    </ng-template>

// react/src/components/EarnedBenefits/EarnedBenefits.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useDispatch, useSelector } from 'react-redux';
import { useAlert } from '../../services/alert/alertService';
import { useMember } from '../../services/member/memberService';
import { NoData } from '../common/NoData/NoData';
import { CardMiniSkeleton } from '../common/CardMiniSkeleton/CardMiniSkeleton';
import { formatDate } from '../../utils/dateUtils';

const Container = styled.div`
  margin-top: 20px;
`;

const Title = styled.h3`
  margin-top: 0;
`;

const BenefitsGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 10px;
  margin-top: 20px;
`;

const BenefitCard = styled.div`
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  padding: 16px;
  height: 140px;
  display: flex;
  align-items: center;
  gap: 10px;
`;

const LogoSection = styled.div`
  width: 50%;
  img {
    max-width: 100%;
    height: auto;
  }
`;

const ContentSection = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 10px;
  max-width: 500px;
`;

const BenefitName = styled.h3`
  margin-top: 10px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
`;

const BenefitDescription = styled.p`
  margin: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
`;

const ExpiryDate = styled.small`
  color: #666;
  line-height: 1.5;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
`;

interface Benefit {
  name: string;
  desc: string;
  expirationDate?: string;
  ext?: {
    isBenefit: boolean;
  };
}

export const EarnedBenefits: React.FC = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [memberBenefits, setMemberBenefits] = useState<Benefit[]>([]);
  const { showError } = useAlert();
  const { getOffers } = useMember();
  const location = useSelector((state: any) => state.location.location);
  const memberInfo = useSelector((state: any) => state.member);

  useEffect(() => {
    if (memberInfo?._id) {
      getMemberBenefits();
    }
  }, [memberInfo, location]);

  const getMemberBenefits = async () => {
    try {
      const offers = await getOffers(memberInfo._id, location.number ?? location);
      const benefits = offers.filter((offer: Benefit) => offer.ext?.isBenefit);
      setMemberBenefits(benefits);
      setIsLoading(false);
    } catch (error: any) {
      showError(error?.error?.error || error?.message);
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div style={{ marginTop: '50px' }}>
        <CardMiniSkeleton />
      </div>
    );
  }

  if (!memberBenefits.length) {
    return <NoData>No Benefits available.</NoData>;
  }

  return (
    <Container>
      <Title>Available Member Benefits ({memberBenefits.length})</Title>
      <BenefitsGrid>
        {memberBenefits.map((benefit, index) => (
          <BenefitCard key={index}>
            <LogoSection>
              <img src="/assets/bclc-logo.png" alt="BCLC Logo" />
            </LogoSection>
            <ContentSection>
              <BenefitName>{benefit.name}</BenefitName>
              <BenefitDescription>{benefit.desc}</BenefitDescription>
              {benefit.expirationDate && (
                <ExpiryDate>
                  Expires {formatDate(benefit.expirationDate)}
                </ExpiryDate>
              )}
            </ContentSection>
          </BenefitCard>
        ))}
      </BenefitsGrid>
    </Container>
  );
};
