// react/src/components/BuyCoupon/BuyCoupon.tsx
import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { useActivity } from '../../services/activity/activityService';
import { useAlert } from '../../services/alert/alertService';
import { Coupon } from '../../models/coupon';
import { Member } from '../../models/member';
import { ActivityRequest } from '../../models/activity';

interface BuyCouponProps {
  memberInfo: Member;
  refresh: boolean;
  onClose: (refresh: boolean) => void;
}

interface CouponWithCount extends Coupon {
  count: number;
  ext: {
    rewardCost: number;
    isSelected: boolean;
  };
}

const Container = styled.div`
  padding: 20px;
`;

const CouponCard = styled.div`
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 16px;
  margin-bottom: 16px;
  background-color: white;
`;

const CouponHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
`;

const CouponName = styled.h3`
  margin: 0;
  color: var(--primary-color);
`;

const CouponCost = styled.span`
  color: var(--secondary-color);
  font-weight: bold;
`;

const CounterContainer = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
`;

const CounterButton = styled.button`
  padding: 8px 16px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  background-color: white;
  cursor: pointer;
  &:hover {
    background-color: #f5f5f5;
  }
`;

const BuyButton = styled.button`
  padding: 12px 24px;
  background-color: var(--primary-color);
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  margin-top: 16px;
  &:hover {
    background-color: var(--primary-color-dark);
  }
`;

export const BuyCoupon: React.FC<BuyCouponProps> = ({ memberInfo, refresh, onClose }) => {
  const [couponList, setCouponList] = useState<CouponWithCount[]>([]);
  const { getCoupons, getActivity } = useActivity();
  const { showError } = useAlert();

  useEffect(() => {
    if (memberInfo) {
      fetchCoupons();
    }
  }, [memberInfo]);

  useEffect(() => {
    if (refresh) {
      clearCoupons();
    }
  }, [refresh]);

  const fetchCoupons = async () => {
    try {
      const coupons = await getCoupons();
      setCouponList(coupons.map(coupon => ({
        ...coupon,
        count: 0,
        ext: {
          ...coupon?.ext,
          isSelected: false
        }
      }) as CouponWithCount));
    } catch (error: any) {
      showError(error?.error?.error || error?.message || 'Failed to fetch coupons');
    }
  };

  const clearCoupons = () => {
    setCouponList(coupons => 
      coupons.map(coupon => ({ ...coupon, count: 0 }) as CouponWithCount)
    );
  };

  const hasCoupons = () => couponList.some(coupon => coupon.count);
  
  const totalPoints = () => 
    couponList.reduce((acc, coupon) => 
      (coupon.count ?? 0) * coupon.ext.rewardCost + acc, 0
    );

  const updateCouponCount = (index: number, increment: boolean) => {
    setCouponList(coupons => 
      coupons.map((coupon, i) => 
        i === index 
          ? { ...coupon, count: Math.max(0, (coupon.count ?? 0) + (increment ? 1 : -1)) }
          : coupon
      )
    );
  };

  const createPayload = (couponCode: string): ActivityRequest => ({
    type: 'Redemption',
    date: new Date().toISOString(),
    srcChannelType: 'Web',
    srcChannelID: 'Web',
    loyaltyID: memberInfo.loyaltyId,
    couponCode,
  });

  const buyCoupon = async () => {
    if (totalPoints() > memberInfo.purses[0].availBalance) {
      showError('Not enough points to buy the selected coupons');
      return;
    }

    try {
      const requests = couponList
        .filter(coupon => coupon.count)
        .flatMap(coupon => 
          Array(coupon.count).fill(null).map(() => 
            getActivity(createPayload(coupon.name))
          )
        );

      await Promise.all(requests);
      onClose(true);
    } catch (error: any) {
      showError(error?.error?.error || error?.message || 'Failed to buy coupons');
    }
  };

  return (
    <Container>
      {couponList.map((coupon, index) => (
        <CouponCard key={coupon.name}>
          <CouponHeader>
            <CouponName>{coupon.name}</CouponName>
            <CouponCost>{coupon.ext.rewardCost} points</CouponCost>
          </CouponHeader>
          <CounterContainer>
            <CounterButton onClick={() => updateCouponCount(index, false)}>
              -
            </CounterButton>
            <span>{coupon.count ?? 0}</span>
            <CounterButton onClick={() => updateCouponCount(index, true)}>
              +
            </CounterButton>
          </CounterContainer>
        </CouponCard>
      ))}
      {hasCoupons() && (
        <BuyButton onClick={buyCoupon}>
          Buy Coupons ({totalPoints()} points)
        </BuyButton>
      )}
    </Container>
  );
};

// src/app/components/buy-coupon/buy-coupon.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatIconModule } from '@angular/material/icon';
import { MatDividerModule } from '@angular/material/divider';
import { MatCardModule } from '@angular/material/card';
import { ActivityService } from '../../services/activity.service';
import { Member } from '../../models/member';
import { Coupon } from '../../models/coupon';
import { AlertService } from '../../services/alert/alert.service';
import { CommonModule } from '@angular/common';
import { Observable, forkJoin } from 'rxjs';

@Component({
  selector: 'app-buy-coupon',
  standalone: true,
  imports: [
    MatButtonModule,
    FlexLayoutModule,
    MatIconModule,
    MatDividerModule,
    MatCardModule,
    CommonModule,
  ],
  templateUrl: './buy-coupon.component.html',
  styleUrl: './buy-coupon.component.scss',
})
export class BuyCouponComponent implements OnChanges {
  @Output() close: EventEmitter<boolean> = new EventEmitter<boolean>();
  @Input() memberInfo!: Member;
  @Input() refresh = false;

  couponList: Coupon[] = [];

  constructor(
    private activityService: ActivityService,
    private alertService: AlertService
  ) { }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['memberInfo'] && changes['memberInfo'].currentValue) {
      this.getCoupons();
    }
    if (changes['refresh']) {
      this.clearCoupons();
    }
  }

  clearCoupons() {
    this.couponList.forEach((coupon) => (coupon.count = 0));
  }

  getCoupons() {
    this.activityService.getCoupons().subscribe({
      next: (couponList: Coupon[]) => {
        this.couponList = couponList;
      },
      error: (error) => {
        this.alertService.errorAlert(error?.error?.error || error?.message);
      },
    });
  }

  hasCoupons = () => this.couponList.find((coupon) => coupon.count);
  totalPoints = () =>
    this.couponList.reduce(
      (acc, c) => (c.count ?? 0) * c.ext.rewardCost + acc,
      0
    );

  reduceCount(coupon: Coupon) {
    coupon.count = coupon.count ? --coupon.count : 0;
  }

  increaseCount(coupon: Coupon) {
    coupon.count = coupon.count ? ++coupon.count : 1;
  }

  createPayload(couponCode: string) {
    return {
      type: 'Redemption',
      date: new Date(),
      srcChannelType: 'Web',
      loyaltyID: +this.memberInfo.loyaltyId,
      couponCode: couponCode,
    };
  }

  buyCoupon() {
    if (this.totalPoints() > this.memberInfo.purses[0].availBalance) {
      this.alertService.errorAlert(
        'Not enough points to buy the selected coupons'
      );
      return;
    }
    let requests: Observable<any>[] = [];
    this.couponList
      .filter((coupon) => coupon.count)
      .forEach((coupon) => {
        for (let c = 0; c < (coupon.count ?? 0); c++) {
          requests.push(
            this.activityService.getActivity(this.createPayload(coupon.name))
          );
        }
      });
    forkJoin(requests).subscribe({
      next: () => {
        this.closeDrawer(true);
      },
      error: (error) => this.alertService.errorAlert(error?.error?.error || error?.message)
    });
  }

  closeDrawer(refresh: boolean = false) {
    this.close.emit(refresh);
  }
}

<div fxLayout="row" fxLayoutAlign="start center" class="pl-20 pr-20 pt-10 pb-0 mb-10">
    <h3 class="m-0">Buy Coupons</h3>
    <span fxFlex></span>
    <button mat-icon-button (click)="closeDrawer()">
        <mat-icon>close</mat-icon>
    </button>
</div>
<mat-divider></mat-divider>
<div fxLayout="row" fxLayoutAlign="end center" fxLayoutGap="20px" class="mr-15 mt-10">
    <div fxLayout="column mr-10">
        <div class="color-gray">Points Available</div>
        <h1 class="color-primary text-left mt-0 mb-0">{{memberInfo.purses[0].availBalance | number : '1.0-0'}}
        </h1>
    </div>
</div>
<div fxLayout="row wrap" fxLayoutGap="20" class="pl-40 pt-20">
    @for(coupon of couponList; track coupon){
    <mat-card fxFlex="45">
        <div fxLayout="row" fxLayoutAlign="end center" class="pr-20 pt-20">
            
        </div>
        <mat-card-header class="pt-10 mb-20">
            <mat-card-title-group>
                <mat-card-title>
                    <h2 class="color-primary mb-20">{{coupon.desc}}</h2>
                </mat-card-title>
            </mat-card-title-group>
        </mat-card-header>
        <mat-card-content class="mb-20">
            <div fxLayout="row" fxLayoutAlign="start center">
                <h2 class="color-primary mr-5">{{coupon.ext.rewardCost}}</h2>
                <p class="color-gray">RR Points</p>
            </div>
        </mat-card-content>
        <mat-card-actions fxLayout="row" fxLayoutAlign="center center" class="card-action position-relative">
            <div class="circle-1"></div>
            <div class="circle-2"></div>
            <div fxLayout="row" fxLayoutAlign="space-between center" class="count-wrapper">
                <button mat-icon-button [disabled]="!coupon.count" (click)="reduceCount(coupon)">
                    <mat-icon>remove</mat-icon>
                </button>
                <h3>{{coupon.count ?? 0}}</h3>
                <button mat-icon-button (click)="increaseCount(coupon)">
                    <mat-icon>add</mat-icon>
                </button>
            </div>
        </mat-card-actions>
    </mat-card>
    }
</div>
@if(hasCoupons()){
<div fxLayout="row" fxLayoutAlign="center" class="mt-50">
    <div fxLayout="column" fxLayoutGap="20" class="rr-wrapper bg-light-primary p-20">
        <h3 class="text-center color-primary">Coupon Purchase Summary</h3>
        @for(coupon of couponList; track coupon){
        @if(coupon.count){
        <div fxLayout="row" fxLayoutAlign="space-between center">
            <h4>{{coupon.desc}} X {{coupon.count}}</h4>
            <h3>{{coupon.ext.rewardCost * coupon.count | number : '1.0-0'}}</h3>
        </div>
        }
        }

        <div fxLayout="row" fxLayoutAlign="space-between center">
            <h3>RR Points to Spend</h3>
            <h2>{{totalPoints() | number : '1.0-0'}}</h2>
        </div>
    </div>
</div>
<div fxLayout="row" fxLayoutAlign="end center" class="mr-20 mt-30">
    <button mat-button class="mr-20" (click)="closeDrawer()">Cancel</button>
    <button mat-flat-button color="primary" class="h-50 w-150" (click)="buyCoupon()">Purchase</button>
</div>
}
